//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for ageType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all minOccurs="0">
 *         &lt;element name="age-unit" type="{http://sigrec.ClinicalTrialApplication.xsd}age-unitType" minOccurs="0"/>
 *         &lt;element name="min-age" type="{http://sigrec.ClinicalTrialApplication.xsd}optional_type" minOccurs="0"/>
 *         &lt;element name="max-age" type="{http://sigrec.ClinicalTrialApplication.xsd}optional_type" minOccurs="0"/>
 *         &lt;element name="under-eighteen" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="adult" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="elderly" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="in-utero" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="preterm-newborn-infants" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="newborn" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="infant-and-toddler" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="children" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="adolescent" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ageType", propOrder =
{

})
public class AgeType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "age-unit")
    protected AgeUnitType ageUnit;
    @XmlElement(name = "min-age")
    protected OptionalType minAge;
    @XmlElement(name = "max-age")
    protected OptionalType maxAge;
    @XmlElement(name = "under-eighteen")
    protected String underEighteen;
    protected String adult;
    protected String elderly;
    @XmlElement(name = "in-utero")
    protected String inUtero;
    @XmlElement(name = "preterm-newborn-infants")
    protected String pretermNewbornInfants;
    protected String newborn;
    @XmlElement(name = "infant-and-toddler")
    protected String infantAndToddler;
    protected String children;
    protected String adolescent;

    /**
     * Gets the value of the ageUnit property.
     * @return possible object is {@link AgeUnitType }
     */
    public AgeUnitType getAgeUnit()
    {
        return this.ageUnit;
    }

    /**
     * Sets the value of the ageUnit property.
     * @param value allowed object is {@link AgeUnitType }
     */
    public void setAgeUnit(final AgeUnitType value)
    {
        this.ageUnit = value;
    }

    /**
     * Gets the value of the minAge property.
     * @return possible object is {@link OptionalType }
     */
    public OptionalType getMinAge()
    {
        return this.minAge;
    }

    /**
     * Sets the value of the minAge property.
     * @param value allowed object is {@link OptionalType }
     */
    public void setMinAge(final OptionalType value)
    {
        this.minAge = value;
    }

    /**
     * Gets the value of the maxAge property.
     * @return possible object is {@link OptionalType }
     */
    public OptionalType getMaxAge()
    {
        return this.maxAge;
    }

    /**
     * Sets the value of the maxAge property.
     * @param value allowed object is {@link OptionalType }
     */
    public void setMaxAge(final OptionalType value)
    {
        this.maxAge = value;
    }

    /**
     * Gets the value of the underEighteen property.
     * @return possible object is {@link String }
     */
    public String getUnderEighteen()
    {
        return this.underEighteen;
    }

    /**
     * Sets the value of the underEighteen property.
     * @param value allowed object is {@link String }
     */
    public void setUnderEighteen(final String value)
    {
        this.underEighteen = value;
    }

    /**
     * Gets the value of the adult property.
     * @return possible object is {@link String }
     */
    public String getAdult()
    {
        return this.adult;
    }

    /**
     * Sets the value of the adult property.
     * @param value allowed object is {@link String }
     */
    public void setAdult(final String value)
    {
        this.adult = value;
    }

    /**
     * Gets the value of the elderly property.
     * @return possible object is {@link String }
     */
    public String getElderly()
    {
        return this.elderly;
    }

    /**
     * Sets the value of the elderly property.
     * @param value allowed object is {@link String }
     */
    public void setElderly(final String value)
    {
        this.elderly = value;
    }

    /**
     * Gets the value of the inUtero property.
     * @return possible object is {@link String }
     */
    public String getInUtero()
    {
        return this.inUtero;
    }

    /**
     * Sets the value of the inUtero property.
     * @param value allowed object is {@link String }
     */
    public void setInUtero(final String value)
    {
        this.inUtero = value;
    }

    /**
     * Gets the value of the pretermNewbornInfants property.
     * @return possible object is {@link String }
     */
    public String getPretermNewbornInfants()
    {
        return this.pretermNewbornInfants;
    }

    /**
     * Sets the value of the pretermNewbornInfants property.
     * @param value allowed object is {@link String }
     */
    public void setPretermNewbornInfants(final String value)
    {
        this.pretermNewbornInfants = value;
    }

    /**
     * Gets the value of the newborn property.
     * @return possible object is {@link String }
     */
    public String getNewborn()
    {
        return this.newborn;
    }

    /**
     * Sets the value of the newborn property.
     * @param value allowed object is {@link String }
     */
    public void setNewborn(final String value)
    {
        this.newborn = value;
    }

    /**
     * Gets the value of the infantAndToddler property.
     * @return possible object is {@link String }
     */
    public String getInfantAndToddler()
    {
        return this.infantAndToddler;
    }

    /**
     * Sets the value of the infantAndToddler property.
     * @param value allowed object is {@link String }
     */
    public void setInfantAndToddler(final String value)
    {
        this.infantAndToddler = value;
    }

    /**
     * Gets the value of the children property.
     * @return possible object is {@link String }
     */
    public String getChildren()
    {
        return this.children;
    }

    /**
     * Sets the value of the children property.
     * @param value allowed object is {@link String }
     */
    public void setChildren(final String value)
    {
        this.children = value;
    }

    /**
     * Gets the value of the adolescent property.
     * @return possible object is {@link String }
     */
    public String getAdolescent()
    {
        return this.adolescent;
    }

    /**
     * Sets the value of the adolescent property.
     * @param value allowed object is {@link String }
     */
    public void setAdolescent(final String value)
    {
        this.adolescent = value;
    }

}
