//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for age-unitType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="age-unitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="jours" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="semaines" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="mois" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="annees" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "age-unitType", propOrder =
{

})
public class AgeUnitType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    protected String jours;
    protected String semaines;
    protected String mois;
    @XmlElement(name = "ann\u00e9e")
    protected String annees;

    /**
     * Gets the value of the jours property.
     * @return possible object is {@link String }
     */
    public String getJours()
    {
        return this.jours;
    }

    /**
     * Sets the value of the jours property.
     * @param value allowed object is {@link String }
     */
    public void setJours(final String value)
    {
        this.jours = value;
    }

    /**
     * Gets the value of the semaines property.
     * @return possible object is {@link String }
     */
    public String getSemaines()
    {
        return this.semaines;
    }

    /**
     * Sets the value of the semaines property.
     * @param value allowed object is {@link String }
     */
    public void setSemaines(final String value)
    {
        this.semaines = value;
    }

    /**
     * Gets the value of the mois property.
     * @return possible object is {@link String }
     */
    public String getMois()
    {
        return this.mois;
    }

    /**
     * Sets the value of the mois property.
     * @param value allowed object is {@link String }
     */
    public void setMois(final String value)
    {
        this.mois = value;
    }

    /**
     * Gets the value of the annees property.
     * @return possible object is {@link String }
     */
    public String getAnnees()
    {
        return this.annees;
    }

    /**
     * Sets the value of the annees property.
     * @param value allowed object is {@link String }
     */
    public void setAnnees(final String value)
    {
        this.annees = value;
    }

}
