//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for cnilType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cnilType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="methodologie-de-reference" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="declaration-individuelle" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cnilType", propOrder =
{"methodologieDeReference", "declarationIndividuelle" })
public class CnilType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "m\u00e9thodologie-de-r\u00e9f\u00e9rence")
    protected String methodologieDeReference;
    @XmlElement(name = "d\u00e9claration-individuelle")
    protected String declarationIndividuelle;

    /**
     * Gets the value of the methodologieDeReference property.
     * @return possible object is {@link String }
     */
    public String getMethodologieDeReference()
    {
        return this.methodologieDeReference;
    }

    /**
     * Sets the value of the methodologieDeReference property.
     * @param value allowed object is {@link String }
     */
    public void setMethodologieDeReference(final String value)
    {
        this.methodologieDeReference = value;
    }

    /**
     * Gets the value of the declarationIndividuelle property.
     * @return possible object is {@link String }
     */
    public String getDeclarationIndividuelle()
    {
        return this.declarationIndividuelle;
    }

    /**
     * Sets the value of the declarationIndividuelle property.
     * @param value allowed object is {@link String }
     */
    public void setDeclarationIndividuelle(final String value)
    {
        this.declarationIndividuelle = value;
    }

}
