//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for communication-informationType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="communication-informationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="cpp-first-inclusion-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="cpp-last-patient-information-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="cpp-sending-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ac-first-inclusion-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ac-last-patient-information-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ac-sending-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "communication-informationType", propOrder =
{

})
public class CommunicationInformationType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElementRef(name = "cpp-first-inclusion-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> cppFirstInclusionDate;
    @XmlElementRef(name = "cpp-last-patient-information-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> cppLastPatientInformationDate;
    @XmlElementRef(name = "cpp-sending-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> cppSendingDate;
    @XmlElementRef(name = "ac-first-inclusion-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> acFirstInclusionDate;
    @XmlElementRef(name = "ac-last-patient-information-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> acLastPatientInformationDate;
    @XmlElementRef(name = "ac-sending-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> acSendingDate;

    /**
     * Gets the value of the cppFirstInclusionDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getCppFirstInclusionDate()
    {
        return this.cppFirstInclusionDate;
    }

    /**
     * Sets the value of the cppFirstInclusionDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setCppFirstInclusionDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.cppFirstInclusionDate = (value);
    }

    /**
     * Gets the value of the cppLastPatientInformationDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getCppLastPatientInformationDate()
    {
        return this.cppLastPatientInformationDate;
    }

    /**
     * Sets the value of the cppLastPatientInformationDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setCppLastPatientInformationDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.cppLastPatientInformationDate = (value);
    }

    /**
     * Gets the value of the cppSendingDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getCppSendingDate()
    {
        return this.cppSendingDate;
    }

    /**
     * Sets the value of the cppSendingDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setCppSendingDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.cppSendingDate = (value);
    }

    /**
     * Gets the value of the acFirstInclusionDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getAcFirstInclusionDate()
    {
        return this.acFirstInclusionDate;
    }

    /**
     * Sets the value of the acFirstInclusionDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setAcFirstInclusionDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.acFirstInclusionDate = (value);
    }

    /**
     * Gets the value of the acLastPatientInformationDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getAcLastPatientInformationDate()
    {
        return this.acLastPatientInformationDate;
    }

    /**
     * Sets the value of the acLastPatientInformationDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setAcLastPatientInformationDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.acLastPatientInformationDate = (value);
    }

    /**
     * Gets the value of the acSendingDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getAcSendingDate()
    {
        return this.acSendingDate;
    }

    /**
     * Sets the value of the acSendingDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setAcSendingDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.acSendingDate = (value);
    }

}
