//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for competent-authority-declarationType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="competent-authority-declarationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ac-name" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="admissibility-date" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://sigrec.ClinicalTrialApplication.xsd>optional_type">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="closing-admissibility-date" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="decision-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="decision" type="{http://sigrec.ClinicalTrialApplication.xsd}decisionType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "competent-authority-declarationType", propOrder =
{

})
public class CompetentAuthorityDeclarationType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "ac-name")
    protected CompetentAuthorityDeclarationType.AcName acName;
    @XmlElementRef(name = "admissibility-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<CompetentAuthorityDeclarationType.AdmissibilityDate> admissibilityDate;
    @XmlElementRef(name = "closing-admissibility-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<CompetentAuthorityDeclarationType.ClosingAdmissibilityDate> closingAdmissibilityDate;
    @XmlElementRef(name = "decision-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> decisionDate;
    protected DecisionType decision;

    /**
     * Gets the value of the acName property.
     * @return possible object is {@link CompetentAuthorityDeclarationType.AcName }
     */
    public CompetentAuthorityDeclarationType.AcName getAcName()
    {
        return this.acName;
    }

    /**
     * Sets the value of the acName property.
     * @param value allowed object is {@link CompetentAuthorityDeclarationType.AcName }
     */
    public void setAcName(final CompetentAuthorityDeclarationType.AcName value)
    {
        this.acName = value;
    }

    /**
     * Gets the value of the admissibilityDate property.
     * @return possible object is {@link JAXBElement }{@code <}
     * {@link CompetentAuthorityDeclarationType.AdmissibilityDate }{@code >}
     */
    public JAXBElement<CompetentAuthorityDeclarationType.AdmissibilityDate> getAdmissibilityDate()
    {
        return this.admissibilityDate;
    }

    /**
     * Sets the value of the admissibilityDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}
     * {@link CompetentAuthorityDeclarationType.AdmissibilityDate }{@code >}
     */
    public void setAdmissibilityDate(final JAXBElement<CompetentAuthorityDeclarationType.AdmissibilityDate> value)
    {
        this.admissibilityDate = (value);
    }

    /**
     * Gets the value of the closingAdmissibilityDate property.
     * @return possible object is {@link JAXBElement }{@code <}
     * {@link CompetentAuthorityDeclarationType.ClosingAdmissibilityDate }{@code >}
     */
    public JAXBElement<CompetentAuthorityDeclarationType.ClosingAdmissibilityDate> getClosingAdmissibilityDate()
    {
        return this.closingAdmissibilityDate;
    }

    /**
     * Sets the value of the closingAdmissibilityDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}
     * {@link CompetentAuthorityDeclarationType.ClosingAdmissibilityDate }{@code >}
     */
    public void setClosingAdmissibilityDate(final JAXBElement<CompetentAuthorityDeclarationType.ClosingAdmissibilityDate> value)
    {
        this.closingAdmissibilityDate = (value);
    }

    /**
     * Gets the value of the decisionDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getDecisionDate()
    {
        return this.decisionDate;
    }

    /**
     * Sets the value of the decisionDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setDecisionDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.decisionDate = (value);
    }

    /**
     * Gets the value of the decision property.
     * @return possible object is {@link DecisionType }
     */
    public DecisionType getDecision()
    {
        return this.decision;
    }

    /**
     * Sets the value of the decision property.
     * @param value allowed object is {@link DecisionType }
     */
    public void setDecision(final DecisionType value)
    {
        this.decision = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    {"value" })
    public static class AcName
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;
        @XmlValue
        protected String value;
        @XmlAttribute
        protected String id;

        /**
         * Gets the value of the value property.
         * @return possible object is {@link String }
         */
        public String getValue()
        {
            return this.value;
        }

        /**
         * Sets the value of the value property.
         * @param value allowed object is {@link String }
         */
        public void setValue(final String value)
        {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * @return possible object is {@link String }
         */
        public String getId()
        {
            return this.id;
        }

        /**
         * Sets the value of the id property.
         * @param value allowed object is {@link String }
         */
        public void setId(final String value)
        {
            this.id = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://sigrec.ClinicalTrialApplication.xsd>optional_type">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AdmissibilityDate
        extends OptionalType
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    {"value" })
    public static class ClosingAdmissibilityDate
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;
        @XmlValue
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar value;

        /**
         * Gets the value of the value property.
         * @return possible object is {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getValue()
        {
            return this.value;
        }

        /**
         * Sets the value of the value property.
         * @param value allowed object is {@link XMLGregorianCalendar }
         */
        public void setValue(final XMLGregorianCalendar value)
        {
            this.value = value;
        }

    }

}
