//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for ContactDetailsType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="organisation" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="given-name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="middle-name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="family-name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="service" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="address" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="town-city" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="post-code" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="country-iso-code" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="telephone" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fax" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="email" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactDetailsType", propOrder =
{

})
public class ContactDetailsType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    protected String organisation;
    @XmlElement(name = "given-name")
    protected String givenName;
    @XmlElement(name = "middle-name")
    protected String middleName;
    @XmlElement(name = "family-name")
    protected String familyName;
    protected String service;
    protected String address;
    @XmlElement(name = "town-city")
    protected String townCity;
    @XmlElement(name = "post-code")
    protected String postCode;
    @XmlElement(name = "country-iso-code")
    protected String countryIsoCode;
    protected String telephone;
    protected String fax;
    protected String email;

    /**
     * Gets the value of the organisation property.
     * @return possible object is {@link String }
     */
    public String getOrganisation()
    {
        return this.organisation;
    }

    /**
     * Sets the value of the organisation property.
     * @param value allowed object is {@link String }
     */
    public void setOrganisation(final String value)
    {
        this.organisation = value;
    }

    /**
     * Gets the value of the givenName property.
     * @return possible object is {@link String }
     */
    public String getGivenName()
    {
        return this.givenName;
    }

    /**
     * Sets the value of the givenName property.
     * @param value allowed object is {@link String }
     */
    public void setGivenName(final String value)
    {
        this.givenName = value;
    }

    /**
     * Gets the value of the middleName property.
     * @return possible object is {@link String }
     */
    public String getMiddleName()
    {
        return this.middleName;
    }

    /**
     * Sets the value of the middleName property.
     * @param value allowed object is {@link String }
     */
    public void setMiddleName(final String value)
    {
        this.middleName = value;
    }

    /**
     * Gets the value of the familyName property.
     * @return possible object is {@link String }
     */
    public String getFamilyName()
    {
        return this.familyName;
    }

    /**
     * Sets the value of the familyName property.
     * @param value allowed object is {@link String }
     */
    public void setFamilyName(final String value)
    {
        this.familyName = value;
    }

    /**
     * Gets the value of the service property.
     * @return possible object is {@link String }
     */
    public String getService()
    {
        return this.service;
    }

    /**
     * Sets the value of the service property.
     * @param value allowed object is {@link String }
     */
    public void setService(final String value)
    {
        this.service = value;
    }

    /**
     * Gets the value of the address property.
     * @return possible object is {@link String }
     */
    public String getAddress()
    {
        return this.address;
    }

    /**
     * Sets the value of the address property.
     * @param value allowed object is {@link String }
     */
    public void setAddress(final String value)
    {
        this.address = value;
    }

    /**
     * Gets the value of the townCity property.
     * @return possible object is {@link String }
     */
    public String getTownCity()
    {
        return this.townCity;
    }

    /**
     * Sets the value of the townCity property.
     * @param value allowed object is {@link String }
     */
    public void setTownCity(final String value)
    {
        this.townCity = value;
    }

    /**
     * Gets the value of the postCode property.
     * @return possible object is {@link String }
     */
    public String getPostCode()
    {
        return this.postCode;
    }

    /**
     * Sets the value of the postCode property.
     * @param value allowed object is {@link String }
     */
    public void setPostCode(final String value)
    {
        this.postCode = value;
    }

    /**
     * Gets the value of the countryIsoCode property.
     * @return possible object is {@link String }
     */
    public String getCountryIsoCode()
    {
        return this.countryIsoCode;
    }

    /**
     * Sets the value of the countryIsoCode property.
     * @param value allowed object is {@link String }
     */
    public void setCountryIsoCode(final String value)
    {
        this.countryIsoCode = value;
    }

    /**
     * Gets the value of the telephone property.
     * @return possible object is {@link String }
     */
    public String getTelephone()
    {
        return this.telephone;
    }

    /**
     * Sets the value of the telephone property.
     * @param value allowed object is {@link String }
     */
    public void setTelephone(final String value)
    {
        this.telephone = value;
    }

    /**
     * Gets the value of the fax property.
     * @return possible object is {@link String }
     */
    public String getFax()
    {
        return this.fax;
    }

    /**
     * Sets the value of the fax property.
     * @param value allowed object is {@link String }
     */
    public void setFax(final String value)
    {
        this.fax = value;
    }

    /**
     * Gets the value of the email property.
     * @return possible object is {@link String }
     */
    public String getEmail()
    {
        return this.email;
    }

    /**
     * Sets the value of the email property.
     * @param value allowed object is {@link String }
     */
    public void setEmail(final String value)
    {
        this.email = value;
    }

}
