//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for decisionType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="decisionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="autorisee" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="reserves" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="non-autorisee" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "decisionType", propOrder =
{

})
public class DecisionType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "autoris\u00e9e")
    protected String autorisee;
    @XmlElement(name = "r\u00e9serves")
    protected String reserves;
    @XmlElement(name = "non-autoris\u00e9e")
    protected String nonAutorisee;

    /**
     * Gets the value of the autorisee property.
     * @return possible object is {@link String }
     */
    public String getAutorisee()
    {
        return this.autorisee;
    }

    /**
     * Sets the value of the autorisee property.
     * @param value allowed object is {@link String }
     */
    public void setAutorisee(final String value)
    {
        this.autorisee = value;
    }

    /**
     * Gets the value of the reserves property.
     * @return possible object is {@link String }
     */
    public String getReserves()
    {
        return this.reserves;
    }

    /**
     * Sets the value of the reserves property.
     * @param value allowed object is {@link String }
     */
    public void setReserves(final String value)
    {
        this.reserves = value;
    }

    /**
     * Gets the value of the nonAutorisee property.
     * @return possible object is {@link String }
     */
    public String getNonAutorisee()
    {
        return this.nonAutorisee;
    }

    /**
     * Sets the value of the nonAutorisee property.
     * @param value allowed object is {@link String }
     */
    public void setNonAutorisee(final String value)
    {
        this.nonAutorisee = value;
    }

}
