//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for declaration-amendmentType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="declaration-amendmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="substantial-change" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tax" type="{http://sigrec.ClinicalTrialApplication.xsd}TaxType" minOccurs="0"/>
 *         &lt;element name="amendment-type" type="{http://sigrec.ClinicalTrialApplication.xsd}amendment-typeType" minOccurs="0"/>
 *         &lt;element name="declaration-phase-information" type="{http://sigrec.ClinicalTrialApplication.xsd}declaration-phase-informationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="node-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "declaration-amendmentType", propOrder =
{"substantialChange", "tax", "amendmentType", "declarationPhaseInformation" })
public class DeclarationAmendmentType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "substantial-change")
    protected String substantialChange;
    protected TaxType tax;
    @XmlElement(name = "amendment-type")
    protected AmendmentTypeType amendmentType;
    @XmlElement(name = "declaration-phase-information")
    protected DeclarationPhaseInformationType declarationPhaseInformation;
    @XmlAttribute(name = "node-id")
    protected String nodeId;

    /**
     * Gets the value of the substantialChange property.
     * @return possible object is {@link String }
     */
    public String getSubstantialChange()
    {
        return this.substantialChange;
    }

    /**
     * Sets the value of the substantialChange property.
     * @param value allowed object is {@link String }
     */
    public void setSubstantialChange(final String value)
    {
        this.substantialChange = value;
    }

    /**
     * Gets the value of the tax property.
     * @return possible object is {@link TaxType }
     */
    public TaxType getTax()
    {
        return this.tax;
    }

    /**
     * Sets the value of the tax property.
     * @param value allowed object is {@link TaxType }
     */
    public void setTax(final TaxType value)
    {
        this.tax = value;
    }

    /**
     * Gets the value of the amendmentType property.
     * @return possible object is {@link AmendmentTypeType }
     */
    public AmendmentTypeType getAmendmentType()
    {
        return this.amendmentType;
    }

    /**
     * Sets the value of the amendmentType property.
     * @param value allowed object is {@link AmendmentTypeType }
     */
    public void setAmendmentType(final AmendmentTypeType value)
    {
        this.amendmentType = value;
    }

    /**
     * Gets the value of the declarationPhaseInformation property.
     * @return possible object is {@link DeclarationPhaseInformationType }
     */
    public DeclarationPhaseInformationType getDeclarationPhaseInformation()
    {
        return this.declarationPhaseInformation;
    }

    /**
     * Sets the value of the declarationPhaseInformation property.
     * @param value allowed object is {@link DeclarationPhaseInformationType }
     */
    public void setDeclarationPhaseInformation(final DeclarationPhaseInformationType value)
    {
        this.declarationPhaseInformation = value;
    }

    /**
     * Gets the value of the nodeId property.
     * @return possible object is {@link String }
     */
    public String getNodeId()
    {
        return this.nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * @param value allowed object is {@link String }
     */
    public void setNodeId(final String value)
    {
        this.nodeId = value;
    }

}
