//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for declaration-initialeType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="declaration-initialeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tax" type="{http://sigrec.ClinicalTrialApplication.xsd}TaxType" minOccurs="0"/>
 *         &lt;element name="declaration-phase-information" type="{http://sigrec.ClinicalTrialApplication.xsd}declaration-phase-informationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "declaration-initialeType", propOrder =
{"tax", "declarationPhaseInformation" })
public class DeclarationInitialeType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    protected TaxType tax;
    @XmlElement(name = "declaration-phase-information")
    protected DeclarationPhaseInformationType declarationPhaseInformation;

    /**
     * Gets the value of the tax property.
     * @return possible object is {@link TaxType }
     */
    public TaxType getTax()
    {
        return this.tax;
    }

    /**
     * Sets the value of the tax property.
     * @param value allowed object is {@link TaxType }
     */
    public void setTax(final TaxType value)
    {
        this.tax = value;
    }

    /**
     * Gets the value of the declarationPhaseInformation property.
     * @return possible object is {@link DeclarationPhaseInformationType }
     */
    public DeclarationPhaseInformationType getDeclarationPhaseInformation()
    {
        return this.declarationPhaseInformation;
    }

    /**
     * Sets the value of the declarationPhaseInformation property.
     * @param value allowed object is {@link DeclarationPhaseInformationType }
     */
    public void setDeclarationPhaseInformation(final DeclarationPhaseInformationType value)
    {
        this.declarationPhaseInformation = value;
    }

}
