//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for declaration-phaseType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="declaration-phaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="sponsor-protocol-version" type="{http://sigrec.ClinicalTrialApplication.xsd}optional_type" minOccurs="0"/>
 *         &lt;element name="sponsor-protocol-version-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="sponsor-information-note-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="sponsor-consentement-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ethics-committee-declaration" type="{http://sigrec.ClinicalTrialApplication.xsd}ethics-committee-declarationType" minOccurs="0"/>
 *         &lt;element name="competent-authority-declaration" type="{http://sigrec.ClinicalTrialApplication.xsd}competent-authority-declarationType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="node-id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "declaration-phaseType", propOrder =
{

})
public class DeclarationPhaseType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "sponsor-protocol-version")
    protected OptionalType sponsorProtocolVersion;
    @XmlElementRef(name = "sponsor-protocol-version-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> sponsorProtocolVersionDate;
    @XmlElementRef(name = "sponsor-information-note-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> sponsorInformationNoteDate;
    @XmlElementRef(name = "sponsor-consentement-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> sponsorConsentementDate;
    @XmlElement(name = "ethics-committee-declaration")
    protected EthicsCommitteeDeclarationType ethicsCommitteeDeclaration;
    @XmlElement(name = "competent-authority-declaration")
    protected CompetentAuthorityDeclarationType competentAuthorityDeclaration;
    @XmlAttribute(name = "node-id")
    @XmlSchemaType(name = "anySimpleType")
    protected String nodeId;

    /**
     * Gets the value of the sponsorProtocolVersion property.
     * @return possible object is {@link OptionalType }
     */
    public OptionalType getSponsorProtocolVersion()
    {
        return this.sponsorProtocolVersion;
    }

    /**
     * Sets the value of the sponsorProtocolVersion property.
     * @param value allowed object is {@link OptionalType }
     */
    public void setSponsorProtocolVersion(final OptionalType value)
    {
        this.sponsorProtocolVersion = value;
    }

    /**
     * Gets the value of the sponsorProtocolVersionDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getSponsorProtocolVersionDate()
    {
        return this.sponsorProtocolVersionDate;
    }

    /**
     * Sets the value of the sponsorProtocolVersionDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setSponsorProtocolVersionDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.sponsorProtocolVersionDate = (value);
    }

    /**
     * Gets the value of the sponsorInformationNoteDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getSponsorInformationNoteDate()
    {
        return this.sponsorInformationNoteDate;
    }

    /**
     * Sets the value of the sponsorInformationNoteDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setSponsorInformationNoteDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.sponsorInformationNoteDate = (value);
    }

    /**
     * Gets the value of the sponsorConsentementDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getSponsorConsentementDate()
    {
        return this.sponsorConsentementDate;
    }

    /**
     * Sets the value of the sponsorConsentementDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setSponsorConsentementDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.sponsorConsentementDate = (value);
    }

    /**
     * Gets the value of the ethicsCommitteeDeclaration property.
     * @return possible object is {@link EthicsCommitteeDeclarationType }
     */
    public EthicsCommitteeDeclarationType getEthicsCommitteeDeclaration()
    {
        return this.ethicsCommitteeDeclaration;
    }

    /**
     * Sets the value of the ethicsCommitteeDeclaration property.
     * @param value allowed object is {@link EthicsCommitteeDeclarationType }
     */
    public void setEthicsCommitteeDeclaration(final EthicsCommitteeDeclarationType value)
    {
        this.ethicsCommitteeDeclaration = value;
    }

    /**
     * Gets the value of the competentAuthorityDeclaration property.
     * @return possible object is {@link CompetentAuthorityDeclarationType }
     */
    public CompetentAuthorityDeclarationType getCompetentAuthorityDeclaration()
    {
        return this.competentAuthorityDeclaration;
    }

    /**
     * Sets the value of the competentAuthorityDeclaration property.
     * @param value allowed object is {@link CompetentAuthorityDeclarationType }
     */
    public void setCompetentAuthorityDeclaration(final CompetentAuthorityDeclarationType value)
    {
        this.competentAuthorityDeclaration = value;
    }

    /**
     * Gets the value of the nodeId property.
     * @return possible object is {@link String }
     */
    public String getNodeId()
    {
        return this.nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * @param value allowed object is {@link String }
     */
    public void setNodeId(final String value)
    {
        this.nodeId = value;
    }

}
