//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for declarationType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="declarationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version-protocole-number" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://sigrec.ClinicalTrialApplication.xsd>optional_type">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="date-version-protocole" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date-version-note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="date-consentement-note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="admissibility-date" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://sigrec.ClinicalTrialApplication.xsd>optional_type">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="opinion-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="opinion" type="{http://sigrec.ClinicalTrialApplication.xsd}opinionType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="node-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "declarationType", propOrder =
{"versionProtocoleNumber", "dateVersionProtocole", "dateVersionNote", "dateConsentementNote",
 "admissibilityDate", "opinionDate", "opinion" })
public class DeclarationType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "version-protocole-number")
    protected DeclarationType.VersionProtocoleNumber versionProtocoleNumber;
    @XmlElement(name = "date-version-protocole", required = true)
    protected String dateVersionProtocole;
    @XmlElement(name = "date-version-note")
    protected String dateVersionNote;
    @XmlElement(name = "date-consentement-note")
    protected String dateConsentementNote;
    @XmlElement(name = "admissibility-date")
    protected DeclarationType.AdmissibilityDate admissibilityDate;
    @XmlElementRef(name = "opinion-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> opinionDate;
    @XmlElement(required = true)
    protected OpinionType opinion;
    @XmlAttribute(name = "node-id")
    protected String nodeId;

    /**
     * Gets the value of the versionProtocoleNumber property.
     * @return possible object is {@link DeclarationType.VersionProtocoleNumber }
     */
    public DeclarationType.VersionProtocoleNumber getVersionProtocoleNumber()
    {
        return this.versionProtocoleNumber;
    }

    /**
     * Sets the value of the versionProtocoleNumber property.
     * @param value allowed object is {@link DeclarationType.VersionProtocoleNumber }
     */
    public void setVersionProtocoleNumber(final DeclarationType.VersionProtocoleNumber value)
    {
        this.versionProtocoleNumber = value;
    }

    /**
     * Gets the value of the dateVersionProtocole property.
     * @return possible object is {@link String }
     */
    public String getDateVersionProtocole()
    {
        return this.dateVersionProtocole;
    }

    /**
     * Sets the value of the dateVersionProtocole property.
     * @param value allowed object is {@link String }
     */
    public void setDateVersionProtocole(final String value)
    {
        this.dateVersionProtocole = value;
    }

    /**
     * Gets the value of the dateVersionNote property.
     * @return possible object is {@link String }
     */
    public String getDateVersionNote()
    {
        return this.dateVersionNote;
    }

    /**
     * Sets the value of the dateVersionNote property.
     * @param value allowed object is {@link String }
     */
    public void setDateVersionNote(final String value)
    {
        this.dateVersionNote = value;
    }

    /**
     * Gets the value of the dateConsentementNote property.
     * @return possible object is {@link String }
     */
    public String getDateConsentementNote()
    {
        return this.dateConsentementNote;
    }

    /**
     * Sets the value of the dateConsentementNote property.
     * @param value allowed object is {@link String }
     */
    public void setDateConsentementNote(final String value)
    {
        this.dateConsentementNote = value;
    }

    /**
     * Gets the value of the admissibilityDate property.
     * @return possible object is {@link DeclarationType.AdmissibilityDate }
     */
    public DeclarationType.AdmissibilityDate getAdmissibilityDate()
    {
        return this.admissibilityDate;
    }

    /**
     * Sets the value of the admissibilityDate property.
     * @param value allowed object is {@link DeclarationType.AdmissibilityDate }
     */
    public void setAdmissibilityDate(final DeclarationType.AdmissibilityDate value)
    {
        this.admissibilityDate = value;
    }

    /**
     * Gets the value of the opinionDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getOpinionDate()
    {
        return this.opinionDate;
    }

    /**
     * Sets the value of the opinionDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setOpinionDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.opinionDate = (value);
    }

    /**
     * Gets the value of the opinion property.
     * @return possible object is {@link OpinionType }
     */
    public OpinionType getOpinion()
    {
        return this.opinion;
    }

    /**
     * Sets the value of the opinion property.
     * @param value allowed object is {@link OpinionType }
     */
    public void setOpinion(final OpinionType value)
    {
        this.opinion = value;
    }

    /**
     * Gets the value of the nodeId property.
     * @return possible object is {@link String }
     */
    public String getNodeId()
    {
        return this.nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * @param value allowed object is {@link String }
     */
    public void setNodeId(final String value)
    {
        this.nodeId = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://sigrec.ClinicalTrialApplication.xsd>optional_type">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AdmissibilityDate
        extends OptionalType
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://sigrec.ClinicalTrialApplication.xsd>optional_type">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class VersionProtocoleNumber
        extends OptionalType
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;

    }

}
