//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for dispositif-medicalType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dispositif-medicalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="commercial-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="common-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ce-label" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dispositif-class" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="classe-id">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="node-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dispositif-medicalType", propOrder =
{

})
public class DispositifMedicalType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "commercial-name")
    protected String commercialName;
    @XmlElement(name = "common-name")
    protected String commonName;
    @XmlElement(name = "ce-label")
    protected String ceLabel;
    @XmlElement(name = "dispositif-class")
    protected DispositifMedicalType.DispositifClass dispositifClass;
    @XmlAttribute(name = "node-id")
    protected String nodeId;

    /**
     * Gets the value of the commercialName property.
     * @return possible object is {@link String }
     */
    public String getCommercialName()
    {
        return this.commercialName;
    }

    /**
     * Sets the value of the commercialName property.
     * @param value allowed object is {@link String }
     */
    public void setCommercialName(final String value)
    {
        this.commercialName = value;
    }

    /**
     * Gets the value of the commonName property.
     * @return possible object is {@link String }
     */
    public String getCommonName()
    {
        return this.commonName;
    }

    /**
     * Sets the value of the commonName property.
     * @param value allowed object is {@link String }
     */
    public void setCommonName(final String value)
    {
        this.commonName = value;
    }

    /**
     * Gets the value of the ceLabel property.
     * @return possible object is {@link String }
     */
    public String getCeLabel()
    {
        return this.ceLabel;
    }

    /**
     * Sets the value of the ceLabel property.
     * @param value allowed object is {@link String }
     */
    public void setCeLabel(final String value)
    {
        this.ceLabel = value;
    }

    /**
     * Gets the value of the dispositifClass property.
     * @return possible object is {@link DispositifMedicalType.DispositifClass }
     */
    public DispositifMedicalType.DispositifClass getDispositifClass()
    {
        return this.dispositifClass;
    }

    /**
     * Sets the value of the dispositifClass property.
     * @param value allowed object is {@link DispositifMedicalType.DispositifClass }
     */
    public void setDispositifClass(final DispositifMedicalType.DispositifClass value)
    {
        this.dispositifClass = value;
    }

    /**
     * Gets the value of the nodeId property.
     * @return possible object is {@link String }
     */
    public String getNodeId()
    {
        return this.nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * @param value allowed object is {@link String }
     */
    public void setNodeId(final String value)
    {
        this.nodeId = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="classe-id">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    {"value" })
    public static class DispositifClass
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;
        @XmlValue
        protected String value;
        @XmlAttribute(name = "classe-id")
        protected Integer classeId;

        /**
         * Gets the value of the value property.
         * @return possible object is {@link String }
         */
        public String getValue()
        {
            return this.value;
        }

        /**
         * Sets the value of the value property.
         * @param value allowed object is {@link String }
         */
        public void setValue(final String value)
        {
            this.value = value;
        }

        /**
         * Gets the value of the classeId property.
         * @return possible object is {@link Integer }
         */
        public Integer getClasseId()
        {
            return this.classeId;
        }

        /**
         * Sets the value of the classeId property.
         * @param value allowed object is {@link Integer }
         */
        public void setClasseId(final Integer value)
        {
            this.classeId = value;
        }

    }

}
