//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * Identit� CCPPRB
 * <p>
 * Java class for ethics-committee-declarationType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ethics-committee-declarationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="reference-cpp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="identity-ccpprb" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="identity-cpp" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://sigrec.ClinicalTrialApplication.xsd>variableType">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="admissibility-date" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://sigrec.ClinicalTrialApplication.xsd>optional_type">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="opinion-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="opinion" type="{http://sigrec.ClinicalTrialApplication.xsd}opinionType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ethics-committee-declarationType", propOrder =
{

})
public class EthicsCommitteeDeclarationType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "reference-cpp")
    protected String referenceCpp;
    @XmlElement(name = "identity-ccpprb")
    protected String identityCcpprb;
    @XmlElement(name = "identity-cpp")
    protected EthicsCommitteeDeclarationType.IdentityCpp identityCpp;
    @XmlElementRef(name = "admissibility-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<EthicsCommitteeDeclarationType.AdmissibilityDate> admissibilityDate;
    @XmlElementRef(name = "opinion-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> opinionDate;
    protected OpinionType opinion;

    /**
     * Gets the value of the referenceCpp property.
     * @return possible object is {@link String }
     */
    public String getReferenceCpp()
    {
        return this.referenceCpp;
    }

    /**
     * Sets the value of the referenceCpp property.
     * @param value allowed object is {@link String }
     */
    public void setReferenceCpp(final String value)
    {
        this.referenceCpp = value;
    }

    /**
     * Gets the value of the identityCcpprb property.
     * @return possible object is {@link String }
     */
    public String getIdentityCcpprb()
    {
        return this.identityCcpprb;
    }

    /**
     * Sets the value of the identityCcpprb property.
     * @param value allowed object is {@link String }
     */
    public void setIdentityCcpprb(final String value)
    {
        this.identityCcpprb = value;
    }

    /**
     * Gets the value of the identityCpp property.
     * @return possible object is {@link EthicsCommitteeDeclarationType.IdentityCpp }
     */
    public EthicsCommitteeDeclarationType.IdentityCpp getIdentityCpp()
    {
        return this.identityCpp;
    }

    /**
     * Sets the value of the identityCpp property.
     * @param value allowed object is {@link EthicsCommitteeDeclarationType.IdentityCpp }
     */
    public void setIdentityCpp(final EthicsCommitteeDeclarationType.IdentityCpp value)
    {
        this.identityCpp = value;
    }

    /**
     * Gets the value of the admissibilityDate property.
     * @return possible object is {@link JAXBElement }{@code <}
     * {@link EthicsCommitteeDeclarationType.AdmissibilityDate }{@code >}
     */
    public JAXBElement<EthicsCommitteeDeclarationType.AdmissibilityDate> getAdmissibilityDate()
    {
        return this.admissibilityDate;
    }

    /**
     * Sets the value of the admissibilityDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}
     * {@link EthicsCommitteeDeclarationType.AdmissibilityDate }{@code >}
     */
    public void setAdmissibilityDate(final JAXBElement<EthicsCommitteeDeclarationType.AdmissibilityDate> value)
    {
        this.admissibilityDate = (value);
    }

    /**
     * Gets the value of the opinionDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getOpinionDate()
    {
        return this.opinionDate;
    }

    /**
     * Sets the value of the opinionDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setOpinionDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.opinionDate = (value);
    }

    /**
     * Gets the value of the opinion property.
     * @return possible object is {@link OpinionType }
     */
    public OpinionType getOpinion()
    {
        return this.opinion;
    }

    /**
     * Sets the value of the opinion property.
     * @param value allowed object is {@link OpinionType }
     */
    public void setOpinion(final OpinionType value)
    {
        this.opinion = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://sigrec.ClinicalTrialApplication.xsd>optional_type">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AdmissibilityDate
        extends OptionalType
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://sigrec.ClinicalTrialApplication.xsd>variableType">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IdentityCpp
        extends VariableType
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;

    }

}
