//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for fonctionsType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fonctionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="fonction-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fonction-libelle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fonctionsType", propOrder =
{"fonctionIdAndFonctionLibelle" })
public class FonctionsType

    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElementRefs(
    {
     @XmlElementRef(name = "fonction-id", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class),
     @XmlElementRef(name = "fonction-libelle", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class) })
    protected List<JAXBElement<String>> fonctionIdAndFonctionLibelle;

    /**
     * Gets the value of the fonctionIdAndFonctionLibelle property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the fonctionIdAndFonctionLibelle property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getFonctionIdAndFonctionLibelle().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}
     * {@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public List<JAXBElement<String>> getFonctionIdAndFonctionLibelle()
    {
        if (this.fonctionIdAndFonctionLibelle == null)
        {
            this.fonctionIdAndFonctionLibelle = new ArrayList<JAXBElement<String>>();
        }
        return this.fonctionIdAndFonctionLibelle;
    }

    /**
     * Retourne l'identifiant.
     * @return l'identifiant.
     */
    public String getId()
    {
        if (null != this.fonctionIdAndFonctionLibelle.get(0))
        {
            return this.fonctionIdAndFonctionLibelle.get(0).getValue();
        }
        else
        {
            return null;
        }
    }
}
