//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for general-informationType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="general-informationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="summary-trial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="interventional-trial" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="type-recherche" type="{http://sigrec.ClinicalTrialApplication.xsd}TypeRechercheType" minOccurs="0"/>
 *         &lt;element name="objet-recherche" type="{http://sigrec.ClinicalTrialApplication.xsd}ObjetRechercheType" minOccurs="0"/>
 *         &lt;element name="trial-type-and-phase" type="{http://sigrec.ClinicalTrialApplication.xsd}trial-type-and-phaseType" minOccurs="0"/>
 *         &lt;element name="trial-scope" type="{http://sigrec.ClinicalTrialApplication.xsd}trial-scopeType" minOccurs="0"/>
 *         &lt;element name="discipline-information" type="{http://sigrec.ClinicalTrialApplication.xsd}discipline-InformationType" minOccurs="0"/>
 *         &lt;element name="medical-condition" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ICD10-codeInformation" type="{http://sigrec.ClinicalTrialApplication.xsd}ICD10-codeInformationType" minOccurs="0"/>
 *         &lt;element name="medDRA-codeInformation" type="{http://sigrec.ClinicalTrialApplication.xsd}medDRA-codeInformationType" minOccurs="0"/>
 *         &lt;element name="trial-design" type="{http://sigrec.ClinicalTrialApplication.xsd}trial-designType" minOccurs="0"/>
 *         &lt;element name="rare-disease" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="main-objective-of-trial" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="secondary-objectives-of-trial" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sub-story" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sub-story-details" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="principal-inclusion-criteria" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="principal-exclusion-criteria" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="primary-end-points" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="planned-start-date" type="{http://sigrec.ClinicalTrialApplication.xsd}optional_type" minOccurs="0"/>
 *         &lt;element name="planned-end-date" type="{http://sigrec.ClinicalTrialApplication.xsd}optional_type" minOccurs="0"/>
 *         &lt;element name="total-trial-duration-ms-months" type="{http://sigrec.ClinicalTrialApplication.xsd}optional_type" minOccurs="0"/>
 *         &lt;element name="total-trial-recruitment-duration-ms-months" type="{http://sigrec.ClinicalTrialApplication.xsd}optional_type" minOccurs="0"/>
 *         &lt;element name="is-extension-end-date" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="extension-end-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="maximum-treatment-duration" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="maximum-dose-allowed" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="maximum-dose-per-day-or-total" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="end-of-trial-definition" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="estimation-of-trial-duration-ms-years" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="estimation-of-trial-duration-ms-months" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="estimation-of-trial-duration-ms-days" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="estimation-of-trial-duration-worldwide-years" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="estimation-of-trial-duration-worldwide-months" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="estimation-of-trial-duration-worldwide-days" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="funding-agency" type="{http://sigrec.ClinicalTrialApplication.xsd}funding-agencyType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "general-informationType", propOrder =
{

})
public class GeneralInformationType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "summary-trial")
    protected String summaryTrial;
    @XmlElement(name = "interventional-trial")
    protected String interventionalTrial;
    @XmlElement(name = "type-recherche")
    protected TypeRechercheType typeRecherche;
    @XmlElement(name = "objet-recherche")
    protected ObjetRechercheType objetRecherche;
    @XmlElement(name = "trial-type-and-phase")
    protected TrialTypeAndPhaseType trialTypeAndPhase;
    @XmlElement(name = "trial-scope")
    protected TrialScopeType trialScope;
    @XmlElement(name = "discipline-information")
    protected DisciplineInformationType disciplineInformation;
    @XmlElement(name = "medical-condition")
    protected String medicalCondition;
    @XmlElement(name = "ICD10-codeInformation")
    protected ICD10CodeInformationType icd10CodeInformation;
    @XmlElement(name = "medDRA-codeInformation")
    protected MedDRACodeInformationType medDRACodeInformation;
    @XmlElement(name = "trial-design")
    protected TrialDesignType trialDesign;
    @XmlElement(name = "rare-disease")
    protected String rareDisease;
    @XmlElement(name = "main-objective-of-trial")
    protected String mainObjectiveOfTrial;
    @XmlElement(name = "secondary-objectives-of-trial")
    protected String secondaryObjectivesOfTrial;
    @XmlElement(name = "sub-story")
    protected String subStory;
    @XmlElement(name = "sub-story-details")
    protected String subStoryDetails;
    @XmlElement(name = "principal-inclusion-criteria")
    protected String principalInclusionCriteria;
    @XmlElement(name = "principal-exclusion-criteria")
    protected String principalExclusionCriteria;
    @XmlElement(name = "primary-end-points")
    protected String primaryEndPoints;
    @XmlElement(name = "planned-start-date")
    protected OptionalType plannedStartDate;
    @XmlElement(name = "planned-end-date")
    protected OptionalType plannedEndDate;
    @XmlElement(name = "total-trial-duration-ms-months")
    protected OptionalType totalTrialDurationMsMonths;
    @XmlElement(name = "total-trial-recruitment-duration-ms-months")
    protected OptionalType totalTrialRecruitmentDurationMsMonths;
    @XmlElement(name = "is-extension-end-date")
    protected String isExtensionEndDate;
    @XmlElementRef(name = "extension-end-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> extensionEndDate;
    @XmlElement(name = "maximum-treatment-duration")
    protected String maximumTreatmentDuration;
    @XmlElement(name = "maximum-dose-allowed")
    protected String maximumDoseAllowed;
    @XmlElement(name = "maximum-dose-per-day-or-total")
    protected String maximumDosePerDayOrTotal;
    @XmlElement(name = "end-of-trial-definition")
    protected String endOfTrialDefinition;
    @XmlElement(name = "estimation-of-trial-duration-ms-years")
    protected String estimationOfTrialDurationMsYears;
    @XmlElement(name = "estimation-of-trial-duration-ms-months")
    protected String estimationOfTrialDurationMsMonths;
    @XmlElement(name = "estimation-of-trial-duration-ms-days")
    protected String estimationOfTrialDurationMsDays;
    @XmlElement(name = "estimation-of-trial-duration-worldwide-years")
    protected String estimationOfTrialDurationWorldwideYears;
    @XmlElement(name = "estimation-of-trial-duration-worldwide-months")
    protected String estimationOfTrialDurationWorldwideMonths;
    @XmlElement(name = "estimation-of-trial-duration-worldwide-days")
    protected String estimationOfTrialDurationWorldwideDays;
    @XmlElement(name = "funding-agency")
    protected FundingAgencyType fundingAgency;

    /**
     * Gets the value of the summaryTrial property.
     * @return possible object is {@link String }
     */
    public String getSummaryTrial()
    {
        return this.summaryTrial;
    }

    /**
     * Sets the value of the summaryTrial property.
     * @param value allowed object is {@link String }
     */
    public void setSummaryTrial(final String value)
    {
        this.summaryTrial = value;
    }

    /**
     * Gets the value of the interventionalTrial property.
     * @return possible object is {@link String }
     */
    public String getInterventionalTrial()
    {
        return this.interventionalTrial;
    }

    /**
     * Sets the value of the interventionalTrial property.
     * @param value allowed object is {@link String }
     */
    public void setInterventionalTrial(final String value)
    {
        this.interventionalTrial = value;
    }

    /**
     * Gets the value of the typeRecherche property.
     * @return possible object is {@link TypeRechercheType }
     */
    public TypeRechercheType getTypeRecherche()
    {
        return this.typeRecherche;
    }

    /**
     * Sets the value of the typeRecherche property.
     * @param value allowed object is {@link TypeRechercheType }
     */
    public void setTypeRecherche(final TypeRechercheType value)
    {
        this.typeRecherche = value;
    }

    /**
     * Gets the value of the objetRecherche property.
     * @return possible object is {@link ObjetRechercheType }
     */
    public ObjetRechercheType getObjetRecherche()
    {
        return this.objetRecherche;
    }

    /**
     * Sets the value of the objetRecherche property.
     * @param value allowed object is {@link ObjetRechercheType }
     */
    public void setObjetRecherche(final ObjetRechercheType value)
    {
        this.objetRecherche = value;
    }

    /**
     * Gets the value of the trialTypeAndPhase property.
     * @return possible object is {@link TrialTypeAndPhaseType }
     */
    public TrialTypeAndPhaseType getTrialTypeAndPhase()
    {
        return this.trialTypeAndPhase;
    }

    /**
     * Sets the value of the trialTypeAndPhase property.
     * @param value allowed object is {@link TrialTypeAndPhaseType }
     */
    public void setTrialTypeAndPhase(final TrialTypeAndPhaseType value)
    {
        this.trialTypeAndPhase = value;
    }

    /**
     * Gets the value of the trialScope property.
     * @return possible object is {@link TrialScopeType }
     */
    public TrialScopeType getTrialScope()
    {
        return this.trialScope;
    }

    /**
     * Sets the value of the trialScope property.
     * @param value allowed object is {@link TrialScopeType }
     */
    public void setTrialScope(final TrialScopeType value)
    {
        this.trialScope = value;
    }

    /**
     * Gets the value of the disciplineInformation property.
     * @return possible object is {@link DisciplineInformationType }
     */
    public DisciplineInformationType getDisciplineInformation()
    {
        return this.disciplineInformation;
    }

    /**
     * Sets the value of the disciplineInformation property.
     * @param value allowed object is {@link DisciplineInformationType }
     */
    public void setDisciplineInformation(final DisciplineInformationType value)
    {
        this.disciplineInformation = value;
    }

    /**
     * Gets the value of the medicalCondition property.
     * @return possible object is {@link String }
     */
    public String getMedicalCondition()
    {
        return this.medicalCondition;
    }

    /**
     * Sets the value of the medicalCondition property.
     * @param value allowed object is {@link String }
     */
    public void setMedicalCondition(final String value)
    {
        this.medicalCondition = value;
    }

    /**
     * Gets the value of the icd10CodeInformation property.
     * @return possible object is {@link ICD10CodeInformationType }
     */
    public ICD10CodeInformationType getICD10CodeInformation()
    {
        return this.icd10CodeInformation;
    }

    /**
     * Sets the value of the icd10CodeInformation property.
     * @param value allowed object is {@link ICD10CodeInformationType }
     */
    public void setICD10CodeInformation(final ICD10CodeInformationType value)
    {
        this.icd10CodeInformation = value;
    }

    /**
     * Gets the value of the medDRACodeInformation property.
     * @return possible object is {@link MedDRACodeInformationType }
     */
    public MedDRACodeInformationType getMedDRACodeInformation()
    {
        return this.medDRACodeInformation;
    }

    /**
     * Sets the value of the medDRACodeInformation property.
     * @param value allowed object is {@link MedDRACodeInformationType }
     */
    public void setMedDRACodeInformation(final MedDRACodeInformationType value)
    {
        this.medDRACodeInformation = value;
    }

    /**
     * Gets the value of the trialDesign property.
     * @return possible object is {@link TrialDesignType }
     */
    public TrialDesignType getTrialDesign()
    {
        return this.trialDesign;
    }

    /**
     * Sets the value of the trialDesign property.
     * @param value allowed object is {@link TrialDesignType }
     */
    public void setTrialDesign(final TrialDesignType value)
    {
        this.trialDesign = value;
    }

    /**
     * Gets the value of the rareDisease property.
     * @return possible object is {@link String }
     */
    public String getRareDisease()
    {
        return this.rareDisease;
    }

    /**
     * Sets the value of the rareDisease property.
     * @param value allowed object is {@link String }
     */
    public void setRareDisease(final String value)
    {
        this.rareDisease = value;
    }

    /**
     * Gets the value of the mainObjectiveOfTrial property.
     * @return possible object is {@link String }
     */
    public String getMainObjectiveOfTrial()
    {
        return this.mainObjectiveOfTrial;
    }

    /**
     * Sets the value of the mainObjectiveOfTrial property.
     * @param value allowed object is {@link String }
     */
    public void setMainObjectiveOfTrial(final String value)
    {
        this.mainObjectiveOfTrial = value;
    }

    /**
     * Gets the value of the secondaryObjectivesOfTrial property.
     * @return possible object is {@link String }
     */
    public String getSecondaryObjectivesOfTrial()
    {
        return this.secondaryObjectivesOfTrial;
    }

    /**
     * Sets the value of the secondaryObjectivesOfTrial property.
     * @param value allowed object is {@link String }
     */
    public void setSecondaryObjectivesOfTrial(final String value)
    {
        this.secondaryObjectivesOfTrial = value;
    }

    /**
     * Gets the value of the subStory property.
     * @return possible object is {@link String }
     */
    public String getSubStory()
    {
        return this.subStory;
    }

    /**
     * Sets the value of the subStory property.
     * @param value allowed object is {@link String }
     */
    public void setSubStory(final String value)
    {
        this.subStory = value;
    }

    /**
     * Gets the value of the subStoryDetails property.
     * @return possible object is {@link String }
     */
    public String getSubStoryDetails()
    {
        return this.subStoryDetails;
    }

    /**
     * Sets the value of the subStoryDetails property.
     * @param value allowed object is {@link String }
     */
    public void setSubStoryDetails(final String value)
    {
        this.subStoryDetails = value;
    }

    /**
     * Gets the value of the principalInclusionCriteria property.
     * @return possible object is {@link String }
     */
    public String getPrincipalInclusionCriteria()
    {
        return this.principalInclusionCriteria;
    }

    /**
     * Sets the value of the principalInclusionCriteria property.
     * @param value allowed object is {@link String }
     */
    public void setPrincipalInclusionCriteria(final String value)
    {
        this.principalInclusionCriteria = value;
    }

    /**
     * Gets the value of the principalExclusionCriteria property.
     * @return possible object is {@link String }
     */
    public String getPrincipalExclusionCriteria()
    {
        return this.principalExclusionCriteria;
    }

    /**
     * Sets the value of the principalExclusionCriteria property.
     * @param value allowed object is {@link String }
     */
    public void setPrincipalExclusionCriteria(final String value)
    {
        this.principalExclusionCriteria = value;
    }

    /**
     * Gets the value of the primaryEndPoints property.
     * @return possible object is {@link String }
     */
    public String getPrimaryEndPoints()
    {
        return this.primaryEndPoints;
    }

    /**
     * Sets the value of the primaryEndPoints property.
     * @param value allowed object is {@link String }
     */
    public void setPrimaryEndPoints(final String value)
    {
        this.primaryEndPoints = value;
    }

    /**
     * Gets the value of the plannedStartDate property.
     * @return possible object is {@link OptionalType }
     */
    public OptionalType getPlannedStartDate()
    {
        return this.plannedStartDate;
    }

    /**
     * Sets the value of the plannedStartDate property.
     * @param value allowed object is {@link OptionalType }
     */
    public void setPlannedStartDate(final OptionalType value)
    {
        this.plannedStartDate = value;
    }

    /**
     * Gets the value of the plannedEndDate property.
     * @return possible object is {@link OptionalType }
     */
    public OptionalType getPlannedEndDate()
    {
        return this.plannedEndDate;
    }

    /**
     * Sets the value of the plannedEndDate property.
     * @param value allowed object is {@link OptionalType }
     */
    public void setPlannedEndDate(final OptionalType value)
    {
        this.plannedEndDate = value;
    }

    /**
     * Gets the value of the totalTrialDurationMsMonths property.
     * @return possible object is {@link OptionalType }
     */
    public OptionalType getTotalTrialDurationMsMonths()
    {
        return this.totalTrialDurationMsMonths;
    }

    /**
     * Sets the value of the totalTrialDurationMsMonths property.
     * @param value allowed object is {@link OptionalType }
     */
    public void setTotalTrialDurationMsMonths(final OptionalType value)
    {
        this.totalTrialDurationMsMonths = value;
    }

    /**
     * Gets the value of the totalTrialRecruitmentDurationMsMonths property.
     * @return possible object is {@link OptionalType }
     */
    public OptionalType getTotalTrialRecruitmentDurationMsMonths()
    {
        return this.totalTrialRecruitmentDurationMsMonths;
    }

    /**
     * Sets the value of the totalTrialRecruitmentDurationMsMonths property.
     * @param value allowed object is {@link OptionalType }
     */
    public void setTotalTrialRecruitmentDurationMsMonths(final OptionalType value)
    {
        this.totalTrialRecruitmentDurationMsMonths = value;
    }

    /**
     * Gets the value of the isExtensionEndDate property.
     * @return possible object is {@link String }
     */
    public String getIsExtensionEndDate()
    {
        return this.isExtensionEndDate;
    }

    /**
     * Sets the value of the isExtensionEndDate property.
     * @param value allowed object is {@link String }
     */
    public void setIsExtensionEndDate(final String value)
    {
        this.isExtensionEndDate = value;
    }

    /**
     * Gets the value of the extensionEndDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getExtensionEndDate()
    {
        return this.extensionEndDate;
    }

    /**
     * Sets the value of the extensionEndDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setExtensionEndDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.extensionEndDate = (value);
    }

    /**
     * Gets the value of the maximumTreatmentDuration property.
     * @return possible object is {@link String }
     */
    public String getMaximumTreatmentDuration()
    {
        return this.maximumTreatmentDuration;
    }

    /**
     * Sets the value of the maximumTreatmentDuration property.
     * @param value allowed object is {@link String }
     */
    public void setMaximumTreatmentDuration(final String value)
    {
        this.maximumTreatmentDuration = value;
    }

    /**
     * Gets the value of the maximumDoseAllowed property.
     * @return possible object is {@link String }
     */
    public String getMaximumDoseAllowed()
    {
        return this.maximumDoseAllowed;
    }

    /**
     * Sets the value of the maximumDoseAllowed property.
     * @param value allowed object is {@link String }
     */
    public void setMaximumDoseAllowed(final String value)
    {
        this.maximumDoseAllowed = value;
    }

    /**
     * Gets the value of the maximumDosePerDayOrTotal property.
     * @return possible object is {@link String }
     */
    public String getMaximumDosePerDayOrTotal()
    {
        return this.maximumDosePerDayOrTotal;
    }

    /**
     * Sets the value of the maximumDosePerDayOrTotal property.
     * @param value allowed object is {@link String }
     */
    public void setMaximumDosePerDayOrTotal(final String value)
    {
        this.maximumDosePerDayOrTotal = value;
    }

    /**
     * Gets the value of the endOfTrialDefinition property.
     * @return possible object is {@link String }
     */
    public String getEndOfTrialDefinition()
    {
        return this.endOfTrialDefinition;
    }

    /**
     * Sets the value of the endOfTrialDefinition property.
     * @param value allowed object is {@link String }
     */
    public void setEndOfTrialDefinition(final String value)
    {
        this.endOfTrialDefinition = value;
    }

    /**
     * Gets the value of the estimationOfTrialDurationMsYears property.
     * @return possible object is {@link String }
     */
    public String getEstimationOfTrialDurationMsYears()
    {
        return this.estimationOfTrialDurationMsYears;
    }

    /**
     * Sets the value of the estimationOfTrialDurationMsYears property.
     * @param value allowed object is {@link String }
     */
    public void setEstimationOfTrialDurationMsYears(final String value)
    {
        this.estimationOfTrialDurationMsYears = value;
    }

    /**
     * Gets the value of the estimationOfTrialDurationMsMonths property.
     * @return possible object is {@link String }
     */
    public String getEstimationOfTrialDurationMsMonths()
    {
        return this.estimationOfTrialDurationMsMonths;
    }

    /**
     * Sets the value of the estimationOfTrialDurationMsMonths property.
     * @param value allowed object is {@link String }
     */
    public void setEstimationOfTrialDurationMsMonths(final String value)
    {
        this.estimationOfTrialDurationMsMonths = value;
    }

    /**
     * Gets the value of the estimationOfTrialDurationMsDays property.
     * @return possible object is {@link String }
     */
    public String getEstimationOfTrialDurationMsDays()
    {
        return this.estimationOfTrialDurationMsDays;
    }

    /**
     * Sets the value of the estimationOfTrialDurationMsDays property.
     * @param value allowed object is {@link String }
     */
    public void setEstimationOfTrialDurationMsDays(final String value)
    {
        this.estimationOfTrialDurationMsDays = value;
    }

    /**
     * Gets the value of the estimationOfTrialDurationWorldwideYears property.
     * @return possible object is {@link String }
     */
    public String getEstimationOfTrialDurationWorldwideYears()
    {
        return this.estimationOfTrialDurationWorldwideYears;
    }

    /**
     * Sets the value of the estimationOfTrialDurationWorldwideYears property.
     * @param value allowed object is {@link String }
     */
    public void setEstimationOfTrialDurationWorldwideYears(final String value)
    {
        this.estimationOfTrialDurationWorldwideYears = value;
    }

    /**
     * Gets the value of the estimationOfTrialDurationWorldwideMonths property.
     * @return possible object is {@link String }
     */
    public String getEstimationOfTrialDurationWorldwideMonths()
    {
        return this.estimationOfTrialDurationWorldwideMonths;
    }

    /**
     * Sets the value of the estimationOfTrialDurationWorldwideMonths property.
     * @param value allowed object is {@link String }
     */
    public void setEstimationOfTrialDurationWorldwideMonths(final String value)
    {
        this.estimationOfTrialDurationWorldwideMonths = value;
    }

    /**
     * Gets the value of the estimationOfTrialDurationWorldwideDays property.
     * @return possible object is {@link String }
     */
    public String getEstimationOfTrialDurationWorldwideDays()
    {
        return this.estimationOfTrialDurationWorldwideDays;
    }

    /**
     * Sets the value of the estimationOfTrialDurationWorldwideDays property.
     * @param value allowed object is {@link String }
     */
    public void setEstimationOfTrialDurationWorldwideDays(final String value)
    {
        this.estimationOfTrialDurationWorldwideDays = value;
    }

    /**
     * Gets the value of the fundingAgency property.
     * @return possible object is {@link FundingAgencyType }
     */
    public FundingAgencyType getFundingAgency()
    {
        return this.fundingAgency;
    }

    /**
     * Sets the value of the fundingAgency property.
     * @param value allowed object is {@link FundingAgencyType }
     */
    public void setFundingAgency(final FundingAgencyType value)
    {
        this.fundingAgency = value;
    }

}
