//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for inclusion-cumulationType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inclusion-cumulationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="is-use-for-export" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cumulation-begining-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="cumulation-end-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="cumulation-number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="cumul-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inclusion-cumulationType", propOrder =
{

})
public class InclusionCumulationType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "is-use-for-export")
    protected String isUseForExport;
    @XmlElementRef(name = "cumulation-begining-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> cumulationBeginingDate;
    @XmlElementRef(name = "cumulation-end-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> cumulationEndDate;
    @XmlElement(name = "cumulation-number")
    protected String cumulationNumber;
    @XmlAttribute(name = "cumul-id")
    protected String cumulId;

    /**
     * Gets the value of the isUseForExport property.
     * @return possible object is {@link String }
     */
    public String getIsUseForExport()
    {
        return this.isUseForExport;
    }

    /**
     * Sets the value of the isUseForExport property.
     * @param value allowed object is {@link String }
     */
    public void setIsUseForExport(final String value)
    {
        this.isUseForExport = value;
    }

    /**
     * Gets the value of the cumulationBeginingDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getCumulationBeginingDate()
    {
        return this.cumulationBeginingDate;
    }

    /**
     * Sets the value of the cumulationBeginingDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setCumulationBeginingDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.cumulationBeginingDate = (value);
    }

    /**
     * Gets the value of the cumulationEndDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getCumulationEndDate()
    {
        return this.cumulationEndDate;
    }

    /**
     * Sets the value of the cumulationEndDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setCumulationEndDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.cumulationEndDate = (value);
    }

    /**
     * Gets the value of the cumulationNumber property.
     * @return possible object is {@link String }
     */
    public String getCumulationNumber()
    {
        return this.cumulationNumber;
    }

    /**
     * Sets the value of the cumulationNumber property.
     * @param value allowed object is {@link String }
     */
    public void setCumulationNumber(final String value)
    {
        this.cumulationNumber = value;
    }

    /**
     * Gets the value of the cumulId property.
     * @return possible object is {@link String }
     */
    public String getCumulId()
    {
        return this.cumulId;
    }

    /**
     * Sets the value of the cumulId property.
     * @param value allowed object is {@link String }
     */
    public void setCumulId(final String value)
    {
        this.cumulId = value;
    }

}
