//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for Insurance-amendment complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Insurance-amendment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="amendment-number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="beginning-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="end-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Insurance-amendment", propOrder =
{"amendmentNumber", "beginningDate", "endDate" })
@XmlSeeAlso(
{fr.pharma.eclipse.domain.model.sigrec.InsuranceAmendmentsType.Amendment.class })
public class InsuranceAmendment
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "amendment-number")
    protected String amendmentNumber;
    @XmlElementRef(name = "beginning-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> beginningDate;
    @XmlElementRef(name = "end-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> endDate;

    /**
     * Gets the value of the amendmentNumber property.
     * @return possible object is {@link String }
     */
    public String getAmendmentNumber()
    {
        return this.amendmentNumber;
    }

    /**
     * Sets the value of the amendmentNumber property.
     * @param value allowed object is {@link String }
     */
    public void setAmendmentNumber(final String value)
    {
        this.amendmentNumber = value;
    }

    /**
     * Gets the value of the beginningDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getBeginningDate()
    {
        return this.beginningDate;
    }

    /**
     * Sets the value of the beginningDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setBeginningDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.beginningDate = (value);
    }

    /**
     * Gets the value of the endDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getEndDate()
    {
        return this.endDate;
    }

    /**
     * Sets the value of the endDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setEndDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.endDate = (value);
    }

}
