//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for Insurance-amendmentsType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Insurance-amendmentsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="amendment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://sigrec.ClinicalTrialApplication.xsd}Insurance-amendment">
 *                 &lt;attribute name="node-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Insurance-amendmentsType", propOrder =
{"amendment" })
public class InsuranceAmendmentsType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    protected List<InsuranceAmendmentsType.Amendment> amendment;

    /**
     * Gets the value of the amendment property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the amendment property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAmendment().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InsuranceAmendmentsType.Amendment }
     */
    public List<InsuranceAmendmentsType.Amendment> getAmendment()
    {
        if (this.amendment == null)
        {
            this.amendment = new ArrayList<InsuranceAmendmentsType.Amendment>();
        }
        return this.amendment;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://sigrec.ClinicalTrialApplication.xsd}Insurance-amendment">
     *       &lt;attribute name="node-id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Amendment
        extends InsuranceAmendment
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;
        @XmlAttribute(name = "node-id")
        protected String nodeId;

        /**
         * Gets the value of the nodeId property.
         * @return possible object is {@link String }
         */
        public String getNodeId()
        {
            return this.nodeId;
        }

        /**
         * Sets the value of the nodeId property.
         * @param value allowed object is {@link String }
         */
        public void setNodeId(final String value)
        {
            this.nodeId = value;
        }

    }

}
