//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

import fr.pharma.eclipse.domain.model.sigrec.common.BeanSigrec;
import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for InsuranceType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuranceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="insurance-policy-number" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="beginning-validity-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="end-validity-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="given-name" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="idnat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="adress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="post-code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="town-city" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="country-iso-code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="amendments" type="{http://sigrec.ClinicalTrialApplication.xsd}Insurance-amendmentsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="node-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuranceType", propOrder =
{"insurancePolicyNumber", "beginningValidityDate", "endValidityDate", "givenName", "adress",
 "postCode", "townCity", "countryIsoCode", "amendments" })
public class InsuranceType
    extends BeanSigrec
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "insurance-policy-number")
    protected InsuranceType.InsurancePolicyNumber insurancePolicyNumber;
    @XmlElementRef(name = "beginning-validity-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> beginningValidityDate;
    @XmlElementRef(name = "end-validity-date", namespace = "http://sigrec.ClinicalTrialApplication.xsd", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> endValidityDate;
    @XmlElement(name = "given-name")
    protected InsuranceType.GivenName givenName;
    protected String adress;
    @XmlElement(name = "post-code")
    protected String postCode;
    @XmlElement(name = "town-city")
    protected String townCity;
    @XmlElement(name = "country-iso-code")
    protected String countryIsoCode;
    protected InsuranceAmendmentsType amendments;
    @XmlAttribute(name = "node-id")
    protected String nodeId;

    /**
     * Gets the value of the insurancePolicyNumber property.
     * @return possible object is {@link InsuranceType.InsurancePolicyNumber }
     */
    public InsuranceType.InsurancePolicyNumber getInsurancePolicyNumber()
    {
        return this.insurancePolicyNumber;
    }

    /**
     * Sets the value of the insurancePolicyNumber property.
     * @param value allowed object is {@link InsuranceType.InsurancePolicyNumber }
     */
    public void setInsurancePolicyNumber(final InsuranceType.InsurancePolicyNumber value)
    {
        this.insurancePolicyNumber = value;
    }

    /**
     * Gets the value of the beginningValidityDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code
     * >}
     */
    public JAXBElement<XMLGregorianCalendar> getBeginningValidityDate()
    {
        return this.beginningValidityDate;
    }

    /**
     * Sets the value of the beginningValidityDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setBeginningValidityDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.beginningValidityDate = (value);
    }

    /**
     * Gets the value of the endValidityDate property.
     * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code
     * >}
     */
    public JAXBElement<XMLGregorianCalendar> getEndValidityDate()
    {
        return this.endValidityDate;
    }

    /**
     * Sets the value of the endValidityDate property.
     * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }
     * {@code >}
     */
    public void setEndValidityDate(final JAXBElement<XMLGregorianCalendar> value)
    {
        this.endValidityDate = (value);
    }

    /**
     * Gets the value of the givenName property.
     * @return possible object is {@link InsuranceType.GivenName }
     */
    public InsuranceType.GivenName getGivenName()
    {
        return this.givenName;
    }

    /**
     * Sets the value of the givenName property.
     * @param value allowed object is {@link InsuranceType.GivenName }
     */
    public void setGivenName(final InsuranceType.GivenName value)
    {
        this.givenName = value;
    }

    /**
     * Gets the value of the adress property.
     * @return possible object is {@link String }
     */
    public String getAdress()
    {
        return this.adress;
    }

    /**
     * Sets the value of the adress property.
     * @param value allowed object is {@link String }
     */
    public void setAdress(final String value)
    {
        this.adress = value;
    }

    /**
     * Gets the value of the postCode property.
     * @return possible object is {@link String }
     */
    public String getPostCode()
    {
        return this.postCode;
    }

    /**
     * Sets the value of the postCode property.
     * @param value allowed object is {@link String }
     */
    public void setPostCode(final String value)
    {
        this.postCode = value;
    }

    /**
     * Gets the value of the townCity property.
     * @return possible object is {@link String }
     */
    public String getTownCity()
    {
        return this.townCity;
    }

    /**
     * Sets the value of the townCity property.
     * @param value allowed object is {@link String }
     */
    public void setTownCity(final String value)
    {
        this.townCity = value;
    }

    /**
     * Gets the value of the countryIsoCode property.
     * @return possible object is {@link String }
     */
    public String getCountryIsoCode()
    {
        return this.countryIsoCode;
    }

    /**
     * Sets the value of the countryIsoCode property.
     * @param value allowed object is {@link String }
     */
    public void setCountryIsoCode(final String value)
    {
        this.countryIsoCode = value;
    }

    /**
     * Gets the value of the amendments property.
     * @return possible object is {@link InsuranceAmendmentsType }
     */
    public InsuranceAmendmentsType getAmendments()
    {
        return this.amendments;
    }

    /**
     * Sets the value of the amendments property.
     * @param value allowed object is {@link InsuranceAmendmentsType }
     */
    public void setAmendments(final InsuranceAmendmentsType value)
    {
        this.amendments = value;
    }

    /**
     * Gets the value of the nodeId property.
     * @return possible object is {@link String }
     */
    public String getNodeId()
    {
        return this.nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * @param value allowed object is {@link String }
     */
    public void setNodeId(final String value)
    {
        this.nodeId = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="idnat" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    {"value" })
    public static class GivenName
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;
        @XmlValue
        protected String value;
        @XmlAttribute
        protected String idnat;

        /**
         * Gets the value of the value property.
         * @return possible object is {@link String }
         */
        public String getValue()
        {
            return this.value;
        }

        /**
         * Sets the value of the value property.
         * @param value allowed object is {@link String }
         */
        public void setValue(final String value)
        {
            this.value = value;
        }

        /**
         * Gets the value of the idnat property.
         * @return possible object is {@link String }
         */
        public String getIdnat()
        {
            return this.idnat;
        }

        /**
         * Sets the value of the idnat property.
         * @param value allowed object is {@link String }
         */
        public void setIdnat(final String value)
        {
            this.idnat = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    {"value" })
    public static class InsurancePolicyNumber
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;
        @XmlValue
        protected String value;
        @XmlAttribute
        protected String id;

        /**
         * Gets the value of the value property.
         * @return possible object is {@link String }
         */
        public String getValue()
        {
            return this.value;
        }

        /**
         * Sets the value of the value property.
         * @param value allowed object is {@link String }
         */
        public void setValue(final String value)
        {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * @return possible object is {@link String }
         */
        public String getId()
        {
            return this.id;
        }

        /**
         * Sets the value of the id property.
         * @param value allowed object is {@link String }
         */
        public void setId(final String value)
        {
            this.id = value;
        }

    }

}
