//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for medDRA-codeType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="medDRA-codeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="medDRA-classification-code-versions" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="medDRA-classification-code-levels" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="medDRA-classification-code-classifications" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="medDRA-classification-code-terms" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="120"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="node-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "medDRA-codeType", propOrder =
{"medDRAClassificationCodeVersions", "medDRAClassificationCodeLevels",
 "medDRAClassificationCodeClassifications", "medDRAClassificationCodeTerms" })
public class MedDRACodeType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "medDRA-classification-code-versions")
    protected String medDRAClassificationCodeVersions;
    @XmlElement(name = "medDRA-classification-code-levels")
    protected String medDRAClassificationCodeLevels;
    @XmlElement(name = "medDRA-classification-code-classifications")
    protected String medDRAClassificationCodeClassifications;
    @XmlElement(name = "medDRA-classification-code-terms")
    protected String medDRAClassificationCodeTerms;
    @XmlAttribute(name = "node-id")
    protected String nodeId;

    /**
     * Gets the value of the medDRAClassificationCodeVersions property.
     * @return possible object is {@link String }
     */
    public String getMedDRAClassificationCodeVersions()
    {
        return this.medDRAClassificationCodeVersions;
    }

    /**
     * Sets the value of the medDRAClassificationCodeVersions property.
     * @param value allowed object is {@link String }
     */
    public void setMedDRAClassificationCodeVersions(final String value)
    {
        this.medDRAClassificationCodeVersions = value;
    }

    /**
     * Gets the value of the medDRAClassificationCodeLevels property.
     * @return possible object is {@link String }
     */
    public String getMedDRAClassificationCodeLevels()
    {
        return this.medDRAClassificationCodeLevels;
    }

    /**
     * Sets the value of the medDRAClassificationCodeLevels property.
     * @param value allowed object is {@link String }
     */
    public void setMedDRAClassificationCodeLevels(final String value)
    {
        this.medDRAClassificationCodeLevels = value;
    }

    /**
     * Gets the value of the medDRAClassificationCodeClassifications property.
     * @return possible object is {@link String }
     */
    public String getMedDRAClassificationCodeClassifications()
    {
        return this.medDRAClassificationCodeClassifications;
    }

    /**
     * Sets the value of the medDRAClassificationCodeClassifications property.
     * @param value allowed object is {@link String }
     */
    public void setMedDRAClassificationCodeClassifications(final String value)
    {
        this.medDRAClassificationCodeClassifications = value;
    }

    /**
     * Gets the value of the medDRAClassificationCodeTerms property.
     * @return possible object is {@link String }
     */
    public String getMedDRAClassificationCodeTerms()
    {
        return this.medDRAClassificationCodeTerms;
    }

    /**
     * Sets the value of the medDRAClassificationCodeTerms property.
     * @param value allowed object is {@link String }
     */
    public void setMedDRAClassificationCodeTerms(final String value)
    {
        this.medDRAClassificationCodeTerms = value;
    }

    /**
     * Gets the value of the nodeId property.
     * @return possible object is {@link String }
     */
    public String getNodeId()
    {
        return this.nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * @param value allowed object is {@link String }
     */
    public void setNodeId(final String value)
    {
        this.nodeId = value;
    }

}
