//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for medicinal-productType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="medicinal-productType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ATC-code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="node-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "medicinal-productType", propOrder =
{

})
public class MedicinalProductType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    protected String code;
    protected String name;
    @XmlElement(name = "ATC-code")
    protected String atcCode;
    @XmlAttribute(name = "node-id")
    protected String nodeId;

    /**
     * Gets the value of the code property.
     * @return possible object is {@link String }
     */
    public String getCode()
    {
        return this.code;
    }

    /**
     * Sets the value of the code property.
     * @param value allowed object is {@link String }
     */
    public void setCode(final String value)
    {
        this.code = value;
    }

    /**
     * Gets the value of the name property.
     * @return possible object is {@link String }
     */
    public String getName()
    {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is {@link String }
     */
    public void setName(final String value)
    {
        this.name = value;
    }

    /**
     * Gets the value of the atcCode property.
     * @return possible object is {@link String }
     */
    public String getATCCode()
    {
        return this.atcCode;
    }

    /**
     * Sets the value of the atcCode property.
     * @param value allowed object is {@link String }
     */
    public void setATCCode(final String value)
    {
        this.atcCode = value;
    }

    /**
     * Gets the value of the nodeId property.
     * @return possible object is {@link String }
     */
    public String getNodeId()
    {
        return this.nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * @param value allowed object is {@link String }
     */
    public void setNodeId(final String value)
    {
        this.nodeId = value;
    }

}
