//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the fr.pharma.eclipse.domain.model.sigrec package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element
 * declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory
    
{

    private final static QName _InsuranceTypeEndValidityDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "end-validity-date");
    private final static QName _InsuranceTypeBeginningValidityDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "beginning-validity-date");
    private final static QName _TaxTypeSendingDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "sending-date");
    private final static QName _TaxTypeReceiptDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "receipt-date");
    private final static QName _DeclarationPhaseTypeSponsorProtocolVersionDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "sponsor-protocol-version-date");
    private final static QName _DeclarationPhaseTypeSponsorConsentementDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "sponsor-consentement-date");
    private final static QName _DeclarationPhaseTypeSponsorInformationNoteDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "sponsor-information-note-date");
    private final static QName _InclusionTypeSignatureConsentementDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "signature-consentement-date");
    private final static QName _DeclarationTypeOpinionDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "opinion-date");
    private final static QName _InsuranceAmendmentEndDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "end-date");
    private final static QName _InsuranceAmendmentBeginningDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "beginning-date");
    private final static QName _GeneralInformationTypeExtensionEndDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "extension-end-date");
    private final static QName _CompetentAuthorityDeclarationTypeDecisionDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "decision-date");
    private final static QName _CompetentAuthorityDeclarationTypeClosingAdmissibilityDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "closing-admissibility-date");
    private final static QName _CompetentAuthorityDeclarationTypeAdmissibilityDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "admissibility-date");
    private final static QName _CommunicationInformationTypeAcSendingDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "ac-sending-date");
    private final static QName _CommunicationInformationTypeAcLastPatientInformationDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "ac-last-patient-information-date");
    private final static QName _CommunicationInformationTypeCppLastPatientInformationDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "cpp-last-patient-information-date");
    private final static QName _CommunicationInformationTypeCppSendingDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "cpp-sending-date");
    private final static QName _CommunicationInformationTypeCppFirstInclusionDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "cpp-first-inclusion-date");
    private final static QName _CommunicationInformationTypeAcFirstInclusionDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "ac-first-inclusion-date");
    private final static QName _FonctionsTypeFonctionLibelle_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "fonction-libelle");
    private final static QName _FonctionsTypeFonctionId_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "fonction-id");
    private final static QName _InvestigatorProgressTypeDateLastInclusion_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "date-last-inclusion");
    private final static QName _InvestigatorProgressTypeDateReceiptProtocole_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "date-receipt-protocole");
    private final static QName _InvestigatorProgressTypeClosingDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "closing-date");
    private final static QName _InvestigatorProgressTypeDateSigningAgreement_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "date-signing-agreement");
    private final static QName _InvestigatorProgressTypeActualEndDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "actual-end-date");
    private final static QName _InvestigatorProgressTypeActualStartDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "actual-start-date");
    private final static QName _InvestigatorProgressTypeDatePlace_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "date-place");
    private final static QName _OrganizationTypeContractEndDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "contract-end-date");
    private final static QName _OrganizationTypeContractBeginningDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "contract-beginning-date");
    private final static QName _InclusionCumulationTypeCumulationBeginingDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "cumulation-begining-date");
    private final static QName _InclusionCumulationTypeCumulationEndDate_QNAME =
        new QName("http://sigrec.ClinicalTrialApplication.xsd",
                  "cumulation-end-date");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived
     * classes for package: fr.pharma.eclipse.domain.model.sigrec
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link TaxType }
     */
    public TaxType createTaxType()
    {
        return new TaxType();
    }

    /**
     * Create an instance of {@link EthicsCommitteeDeclarationType.IdentityCpp }
     */
    public EthicsCommitteeDeclarationType.IdentityCpp createEthicsCommitteeDeclarationTypeIdentityCpp()
    {
        return new EthicsCommitteeDeclarationType.IdentityCpp();
    }

    /**
     * Create an instance of {@link AmendementInformationType }
     */
    public AmendementInformationType createAmendementInformationType()
    {
        return new AmendementInformationType();
    }

    /**
     * Create an instance of {@link ObjetRechercheType }
     */
    public ObjetRechercheType createObjetRechercheType()
    {
        return new ObjetRechercheType();
    }

    /**
     * Create an instance of {@link DeclarationType.AdmissibilityDate }
     */
    public DeclarationType.AdmissibilityDate createDeclarationTypeAdmissibilityDate()
    {
        return new DeclarationType.AdmissibilityDate();
    }

    /**
     * Create an instance of {@link ServicesType }
     */
    public ServicesType createServicesType()
    {
        return new ServicesType();
    }

    /**
     * Create an instance of {@link InclusionType }
     */
    public InclusionType createInclusionType()
    {
        return new InclusionType();
    }

    /**
     * Create an instance of {@link TrialScopeType }
     */
    public TrialScopeType createTrialScopeType()
    {
        return new TrialScopeType();
    }

    /**
     * Create an instance of {@link OpinionType }
     */
    public OpinionType createOpinionType()
    {
        return new OpinionType();
    }

    /**
     * Create an instance of {@link DeclarationInitialeType }
     */
    public DeclarationInitialeType createDeclarationInitialeType()
    {
        return new DeclarationInitialeType();
    }

    /**
     * Create an instance of {@link TaxType.Amount }
     */
    public TaxType.Amount createTaxTypeAmount()
    {
        return new TaxType.Amount();
    }

    /**
     * Create an instance of {@link DeclarationType }
     */
    public DeclarationType createDeclarationType()
    {
        return new DeclarationType();
    }

    /**
     * Create an instance of {@link InvestigatorType.TypeInvestigator }
     */
    public InvestigatorType.TypeInvestigator createInvestigatorTypeTypeInvestigator()
    {
        return new InvestigatorType.TypeInvestigator();
    }

    /**
     * Create an instance of {@link InclusionCumulationInformationType }
     */
    public InclusionCumulationInformationType createInclusionCumulationInformationType()
    {
        return new InclusionCumulationInformationType();
    }

    /**
     * Create an instance of {@link ICD10CodeInformationType }
     */
    public ICD10CodeInformationType createICD10CodeInformationType()
    {
        return new ICD10CodeInformationType();
    }

    /**
     * Create an instance of {@link InclusionsType }
     */
    public InclusionsType createInclusionsType()
    {
        return new InclusionsType();
    }

    /**
     * Create an instance of {@link TypeRechercheType }
     */
    public TypeRechercheType createTypeRechercheType()
    {
        return new TypeRechercheType();
    }

    /**
     * Create an instance of {@link SigrecMultiTrialsTransfert }
     */
    public SigrecMultiTrialsTransfert createSigrecMultiTrialsTransfert()
    {
        return new SigrecMultiTrialsTransfert();
    }

    /**
     * Create an instance of {@link SigrecTransfertInfoType }
     */
    public SigrecTransfertInfoType createSigrecTransfertInfoType()
    {
        return new SigrecTransfertInfoType();
    }

    /**
     * Create an instance of {@link DisciplineInformationType }
     */
    public DisciplineInformationType createDisciplineInformationType()
    {
        return new DisciplineInformationType();
    }

    /**
     * Create an instance of {@link InvestigatorProgressType.AgreementSignatory }
     */
    public InvestigatorProgressType.AgreementSignatory createInvestigatorProgressTypeAgreementSignatory()
    {
        return new InvestigatorProgressType.AgreementSignatory();
    }

    /**
     * Create an instance of {@link CompetentAuthorityDeclarationType.ClosingAdmissibilityDate }
     */
    public CompetentAuthorityDeclarationType.ClosingAdmissibilityDate createCompetentAuthorityDeclarationTypeClosingAdmissibilityDate()
    {
        return new CompetentAuthorityDeclarationType.ClosingAdmissibilityDate();
    }

    /**
     * Create an instance of {@link OrganizationType }
     */
    public OrganizationType createOrganizationType()
    {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link DeclarationType.VersionProtocoleNumber }
     */
    public DeclarationType.VersionProtocoleNumber createDeclarationTypeVersionProtocoleNumber()
    {
        return new DeclarationType.VersionProtocoleNumber();
    }

    /**
     * Create an instance of {@link InvestigatorType.ValidatorInformation }
     */
    public InvestigatorType.ValidatorInformation createInvestigatorTypeValidatorInformation()
    {
        return new InvestigatorType.ValidatorInformation();
    }

    /**
     * Create an instance of {@link PopulationOfTrialSubjectsType }
     */
    public PopulationOfTrialSubjectsType createPopulationOfTrialSubjectsType()
    {
        return new PopulationOfTrialSubjectsType();
    }

    /**
     * Create an instance of {@link InsuranceAmendmentsType.Amendment }
     */
    public InsuranceAmendmentsType.Amendment createInsuranceAmendmentsTypeAmendment()
    {
        return new InsuranceAmendmentsType.Amendment();
    }

    /**
     * Create an instance of {@link CentralTechnicalFacilityType }
     */
    public CentralTechnicalFacilityType createCentralTechnicalFacilityType()
    {
        return new CentralTechnicalFacilityType();
    }

    /**
     * Create an instance of {@link IntervenantType }
     */
    public IntervenantType createIntervenantType()
    {
        return new IntervenantType();
    }

    /**
     * Create an instance of {@link MedDRACodeInformationType }
     */
    public MedDRACodeInformationType createMedDRACodeInformationType()
    {
        return new MedDRACodeInformationType();
    }

    /**
     * Create an instance of {@link MedicinalProductType }
     */
    public MedicinalProductType createMedicinalProductType()
    {
        return new MedicinalProductType();
    }

    /**
     * Create an instance of {@link DispositifMedicalInformationType }
     */
    public DispositifMedicalInformationType createDispositifMedicalInformationType()
    {
        return new DispositifMedicalInformationType();
    }

    /**
     * Create an instance of {@link EthicsCommitteeDeclarationType.AdmissibilityDate }
     */
    public EthicsCommitteeDeclarationType.AdmissibilityDate createEthicsCommitteeDeclarationTypeAdmissibilityDate()
    {
        return new EthicsCommitteeDeclarationType.AdmissibilityDate();
    }

    /**
     * Create an instance of {@link DeclarationPhaseInformationType }
     */
    public DeclarationPhaseInformationType createDeclarationPhaseInformationType()
    {
        return new DeclarationPhaseInformationType();
    }

    /**
     * Create an instance of {@link ICD10ClassificationCodeType }
     */
    public ICD10ClassificationCodeType createICD10ClassificationCodeType()
    {
        return new ICD10ClassificationCodeType();
    }

    /**
     * Create an instance of {@link TrialEchangeType }
     */
    public TrialEchangeType createTrialEchangeType()
    {
        return new TrialEchangeType();
    }

    /**
     * Create an instance of {@link FundingAgencyType }
     */
    public FundingAgencyType createFundingAgencyType()
    {
        return new FundingAgencyType();
    }

    /**
     * Create an instance of {@link AgeUnitType }
     */
    public AgeUnitType createAgeUnitType()
    {
        return new AgeUnitType();
    }

    /**
     * Create an instance of {@link AgencyType }
     */
    public AgencyType createAgencyType()
    {
        return new AgencyType();
    }

    /**
     * Create an instance of {@link FonctionsType }
     */
    public FonctionsType createFonctionsType()
    {
        return new FonctionsType();
    }

    /**
     * Create an instance of {@link TrialType }
     */
    public TrialType createTrialType()
    {
        return new TrialType();
    }

    /**
     * Create an instance of {@link SponsorInformationType }
     */
    public SponsorInformationType createSponsorInformationType()
    {
        return new SponsorInformationType();
    }

    /**
     * Create an instance of {@link OptionalType }
     */
    public OptionalType createOptionalType()
    {
        return new OptionalType();
    }

    /**
     * Create an instance of {@link TrialTypeAndPhaseType }
     */
    public TrialTypeAndPhaseType createTrialTypeAndPhaseType()
    {
        return new TrialTypeAndPhaseType();
    }

    /**
     * Create an instance of {@link CompetentAuthorityDeclarationType.AdmissibilityDate }
     */
    public CompetentAuthorityDeclarationType.AdmissibilityDate createCompetentAuthorityDeclarationTypeAdmissibilityDate()
    {
        return new CompetentAuthorityDeclarationType.AdmissibilityDate();
    }

    /**
     * Create an instance of {@link InsuranceAmendmentsType }
     */
    public InsuranceAmendmentsType createInsuranceAmendmentsType()
    {
        return new InsuranceAmendmentsType();
    }

    /**
     * Create an instance of {@link fr.pharma.eclipse.domain.model.sigrec.SponsorType.SponsorType }
     */
    public fr.pharma.eclipse.domain.model.sigrec.SponsorType.SponsorSsType createSponsorTypeSponsorType()
    {
        return new fr.pharma.eclipse.domain.model.sigrec.SponsorType.SponsorSsType();
    }

    /**
     * Create an instance of {@link DisciplineType }
     */
    public DisciplineType createDisciplineType()
    {
        return new DisciplineType();
    }

    /**
     * Create an instance of {@link MultiTrialEchangeType }
     */
    public MultiTrialEchangeType createMultiTrialEchangeType()
    {
        return new MultiTrialEchangeType();
    }

    /**
     * Create an instance of {@link InsuranceType }
     */
    public InsuranceType createInsuranceType()
    {
        return new InsuranceType();
    }

    /**
     * Create an instance of {@link PlannedNumbersType }
     */
    public PlannedNumbersType createPlannedNumbersType()
    {
        return new PlannedNumbersType();
    }

    /**
     * Create an instance of {@link MedicinalProductsType }
     */
    public MedicinalProductsType createMedicinalProductsType()
    {
        return new MedicinalProductsType();
    }

    /**
     * Create an instance of
     * {@link fr.pharma.eclipse.domain.model.sigrec.SponsorType.SponsorCategory }
     */
    public fr.pharma.eclipse.domain.model.sigrec.SponsorType.SponsorCategory createSponsorTypeSponsorCategory()
    {
        return new fr.pharma.eclipse.domain.model.sigrec.SponsorType.SponsorCategory();
    }

    /**
     * Create an instance of {@link DispositifMedicalType.DispositifClass }
     */
    public DispositifMedicalType.DispositifClass createDispositifMedicalTypeDispositifClass()
    {
        return new DispositifMedicalType.DispositifClass();
    }

    /**
     * Create an instance of {@link GeneralInformationType }
     */
    public GeneralInformationType createGeneralInformationType()
    {
        return new GeneralInformationType();
    }

    /**
     * Create an instance of {@link InvestigatorType }
     */
    public InvestigatorType createInvestigatorType()
    {
        return new InvestigatorType();
    }

    /**
     * Create an instance of {@link MultiTrialType }
     */
    public MultiTrialType createMultiTrialType()
    {
        return new MultiTrialType();
    }

    /**
     * Create an instance of {@link ContactDetailsType }
     */
    public ContactDetailsType createContactDetailsType()
    {
        return new ContactDetailsType();
    }

    /**
     * Create an instance of {@link DecisionType }
     */
    public DecisionType createDecisionType()
    {
        return new DecisionType();
    }

    /**
     * Create an instance of {@link RegulatoryInformationType.InsuranceInformation }
     */
    public RegulatoryInformationType.InsuranceInformation createRegulatoryInformationTypeInsuranceInformation()
    {
        return new RegulatoryInformationType.InsuranceInformation();
    }

    /**
     * Create an instance of {@link DeclarationAmendmentType }
     */
    public DeclarationAmendmentType createDeclarationAmendmentType()
    {
        return new DeclarationAmendmentType();
    }

    /**
     * Create an instance of {@link CommunicationInformationType }
     */
    public CommunicationInformationType createCommunicationInformationType()
    {
        return new CommunicationInformationType();
    }

    /**
     * Create an instance of {@link CompetentAuthorityDeclarationType }
     */
    public CompetentAuthorityDeclarationType createCompetentAuthorityDeclarationType()
    {
        return new CompetentAuthorityDeclarationType();
    }

    /**
     * Create an instance of {@link InsuranceType.InsurancePolicyNumber }
     */
    public InsuranceType.InsurancePolicyNumber createInsuranceTypeInsurancePolicyNumber()
    {
        return new InsuranceType.InsurancePolicyNumber();
    }

    /**
     * Create an instance of {@link TrialMonitoringFacilityType }
     */
    public TrialMonitoringFacilityType createTrialMonitoringFacilityType()
    {
        return new TrialMonitoringFacilityType();
    }

    /**
     * Create an instance of {@link RegulatoryInformationType }
     */
    public RegulatoryInformationType createRegulatoryInformationType()
    {
        return new RegulatoryInformationType();
    }

    /**
     * Create an instance of {@link IntervenantsType.Intervenant }
     */
    public IntervenantsType.Intervenant createIntervenantsTypeIntervenant()
    {
        return new IntervenantsType.Intervenant();
    }

    /**
     * Create an instance of {@link EthicsCommitteeDeclarationType }
     */
    public EthicsCommitteeDeclarationType createEthicsCommitteeDeclarationType()
    {
        return new EthicsCommitteeDeclarationType();
    }

    /**
     * Create an instance of {@link CompetentAuthorityDeclarationType.AcName }
     */
    public CompetentAuthorityDeclarationType.AcName createCompetentAuthorityDeclarationTypeAcName()
    {
        return new CompetentAuthorityDeclarationType.AcName();
    }

    /**
     * Create an instance of {@link TrialDesignType }
     */
    public TrialDesignType createTrialDesignType()
    {
        return new TrialDesignType();
    }

    /**
     * Create an instance of {@link fr.pharma.eclipse.domain.model.sigrec.SponsorType }
     */
    public fr.pharma.eclipse.domain.model.sigrec.SponsorType createSponsorType()
    {
        return new fr.pharma.eclipse.domain.model.sigrec.SponsorType();
    }

    /**
     * Create an instance of {@link CroType }
     */
    public CroType createCroType()
    {
        return new CroType();
    }

    /**
     * Create an instance of {@link MedDRACodeType }
     */
    public MedDRACodeType createMedDRACodeType()
    {
        return new MedDRACodeType();
    }

    /**
     * Create an instance of {@link InsuranceInformationType }
     */
    public InsuranceInformationType createInsuranceInformationType()
    {
        return new InsuranceInformationType();
    }

    /**
     * Create an instance of {@link DeclarationPhaseType }
     */
    public DeclarationPhaseType createDeclarationPhaseType()
    {
        return new DeclarationPhaseType();
    }

    /**
     * Create an instance of {@link AgeType }
     */
    public AgeType createAgeType()
    {
        return new AgeType();
    }

    /**
     * Create an instance of {@link InsuranceAmendment }
     */
    public InsuranceAmendment createInsuranceAmendment()
    {
        return new InsuranceAmendment();
    }

    /**
     * Create an instance of {@link IntervenantsType }
     */
    public IntervenantsType createIntervenantsType()
    {
        return new IntervenantsType();
    }

    /**
     * Create an instance of {@link VariableType }
     */
    public VariableType createVariableType()
    {
        return new VariableType();
    }

    /**
     * Create an instance of {@link TrialIdentificationType }
     */
    public TrialIdentificationType createTrialIdentificationType()
    {
        return new TrialIdentificationType();
    }

    /**
     * Create an instance of {@link DispositifMedicalType }
     */
    public DispositifMedicalType createDispositifMedicalType()
    {
        return new DispositifMedicalType();
    }

    /**
     * Create an instance of {@link InvestigatorProgressType }
     */
    public InvestigatorProgressType createInvestigatorProgressType()
    {
        return new InvestigatorProgressType();
    }

    /**
     * Create an instance of {@link AmendmentTypeType }
     */
    public AmendmentTypeType createAmendmentTypeType()
    {
        return new AmendmentTypeType();
    }

    /**
     * Create an instance of {@link InsuranceType.GivenName }
     */
    public InsuranceType.GivenName createInsuranceTypeGivenName()
    {
        return new InsuranceType.GivenName();
    }

    /**
     * Create an instance of {@link CnilType }
     */
    public CnilType createCnilType()
    {
        return new CnilType();
    }

    /**
     * Create an instance of {@link ProposedClinicalTrialSitesType }
     */
    public ProposedClinicalTrialSitesType createProposedClinicalTrialSitesType()
    {
        return new ProposedClinicalTrialSitesType();
    }

    /**
     * Create an instance of {@link InclusionCumulationType }
     */
    public InclusionCumulationType createInclusionCumulationType()
    {
        return new InclusionCumulationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "end-validity-date", scope = InsuranceType.class)
    public JAXBElement<XMLGregorianCalendar> createInsuranceTypeEndValidityDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InsuranceTypeEndValidityDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InsuranceType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "beginning-validity-date", scope = InsuranceType.class)
    public JAXBElement<XMLGregorianCalendar> createInsuranceTypeBeginningValidityDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InsuranceTypeBeginningValidityDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InsuranceType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "sending-date", scope = TaxType.class)
    public JAXBElement<XMLGregorianCalendar> createTaxTypeSendingDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._TaxTypeSendingDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     TaxType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "receipt-date", scope = TaxType.class)
    public JAXBElement<XMLGregorianCalendar> createTaxTypeReceiptDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._TaxTypeReceiptDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     TaxType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "sponsor-protocol-version-date", scope = DeclarationPhaseType.class)
    public JAXBElement<XMLGregorianCalendar> createDeclarationPhaseTypeSponsorProtocolVersionDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._DeclarationPhaseTypeSponsorProtocolVersionDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     DeclarationPhaseType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "sponsor-consentement-date", scope = DeclarationPhaseType.class)
    public JAXBElement<XMLGregorianCalendar> createDeclarationPhaseTypeSponsorConsentementDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._DeclarationPhaseTypeSponsorConsentementDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     DeclarationPhaseType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "sponsor-information-note-date", scope = DeclarationPhaseType.class)
    public JAXBElement<XMLGregorianCalendar> createDeclarationPhaseTypeSponsorInformationNoteDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._DeclarationPhaseTypeSponsorInformationNoteDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     DeclarationPhaseType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "signature-consentement-date", scope = InclusionType.class)
    public JAXBElement<XMLGregorianCalendar> createInclusionTypeSignatureConsentementDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InclusionTypeSignatureConsentementDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InclusionType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "opinion-date", scope = DeclarationType.class)
    public JAXBElement<XMLGregorianCalendar> createDeclarationTypeOpinionDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._DeclarationTypeOpinionDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     DeclarationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "end-date", scope = InsuranceAmendment.class)
    public JAXBElement<XMLGregorianCalendar> createInsuranceAmendmentEndDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InsuranceAmendmentEndDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InsuranceAmendment.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "beginning-date", scope = InsuranceAmendment.class)
    public JAXBElement<XMLGregorianCalendar> createInsuranceAmendmentBeginningDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InsuranceAmendmentBeginningDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InsuranceAmendment.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "extension-end-date", scope = GeneralInformationType.class)
    public JAXBElement<XMLGregorianCalendar> createGeneralInformationTypeExtensionEndDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._GeneralInformationTypeExtensionEndDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     GeneralInformationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "sponsor-protocol-version-date", scope = TrialIdentificationType.class)
    public JAXBElement<String> createTrialIdentificationTypeSponsorProtocolVersionDate(final String value)
    {
        return new JAXBElement<String>(ObjectFactory._DeclarationPhaseTypeSponsorProtocolVersionDate_QNAME,
                                       String.class,
                                       TrialIdentificationType.class,
                                       value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "decision-date", scope = CompetentAuthorityDeclarationType.class)
    public JAXBElement<XMLGregorianCalendar> createCompetentAuthorityDeclarationTypeDecisionDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._CompetentAuthorityDeclarationTypeDecisionDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     CompetentAuthorityDeclarationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link CompetentAuthorityDeclarationType.ClosingAdmissibilityDate }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "closing-admissibility-date", scope = CompetentAuthorityDeclarationType.class)
    public JAXBElement<CompetentAuthorityDeclarationType.ClosingAdmissibilityDate> createCompetentAuthorityDeclarationTypeClosingAdmissibilityDate(final CompetentAuthorityDeclarationType.ClosingAdmissibilityDate value)
    {
        return new JAXBElement<CompetentAuthorityDeclarationType.ClosingAdmissibilityDate>(ObjectFactory._CompetentAuthorityDeclarationTypeClosingAdmissibilityDate_QNAME,
                                                                                           CompetentAuthorityDeclarationType.ClosingAdmissibilityDate.class,
                                                                                           CompetentAuthorityDeclarationType.class,
                                                                                           value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link CompetentAuthorityDeclarationType.AdmissibilityDate }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "admissibility-date", scope = CompetentAuthorityDeclarationType.class)
    public JAXBElement<CompetentAuthorityDeclarationType.AdmissibilityDate> createCompetentAuthorityDeclarationTypeAdmissibilityDate(final CompetentAuthorityDeclarationType.AdmissibilityDate value)
    {
        return new JAXBElement<CompetentAuthorityDeclarationType.AdmissibilityDate>(ObjectFactory._CompetentAuthorityDeclarationTypeAdmissibilityDate_QNAME,
                                                                                    CompetentAuthorityDeclarationType.AdmissibilityDate.class,
                                                                                    CompetentAuthorityDeclarationType.class,
                                                                                    value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "ac-sending-date", scope = CommunicationInformationType.class)
    public JAXBElement<XMLGregorianCalendar> createCommunicationInformationTypeAcSendingDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._CommunicationInformationTypeAcSendingDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     CommunicationInformationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "ac-last-patient-information-date", scope = CommunicationInformationType.class)
    public JAXBElement<XMLGregorianCalendar> createCommunicationInformationTypeAcLastPatientInformationDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._CommunicationInformationTypeAcLastPatientInformationDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     CommunicationInformationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "cpp-last-patient-information-date", scope = CommunicationInformationType.class)
    public JAXBElement<XMLGregorianCalendar> createCommunicationInformationTypeCppLastPatientInformationDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._CommunicationInformationTypeCppLastPatientInformationDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     CommunicationInformationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "cpp-sending-date", scope = CommunicationInformationType.class)
    public JAXBElement<XMLGregorianCalendar> createCommunicationInformationTypeCppSendingDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._CommunicationInformationTypeCppSendingDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     CommunicationInformationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "cpp-first-inclusion-date", scope = CommunicationInformationType.class)
    public JAXBElement<XMLGregorianCalendar> createCommunicationInformationTypeCppFirstInclusionDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._CommunicationInformationTypeCppFirstInclusionDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     CommunicationInformationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "ac-first-inclusion-date", scope = CommunicationInformationType.class)
    public JAXBElement<XMLGregorianCalendar> createCommunicationInformationTypeAcFirstInclusionDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._CommunicationInformationTypeAcFirstInclusionDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     CommunicationInformationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "fonction-libelle", scope = FonctionsType.class)
    public JAXBElement<String> createFonctionsTypeFonctionLibelle(final String value)
    {
        return new JAXBElement<String>(ObjectFactory._FonctionsTypeFonctionLibelle_QNAME,
                                       String.class,
                                       FonctionsType.class,
                                       value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "fonction-id", scope = FonctionsType.class)
    public JAXBElement<String> createFonctionsTypeFonctionId(final String value)
    {
        return new JAXBElement<String>(ObjectFactory._FonctionsTypeFonctionId_QNAME,
                                       String.class,
                                       FonctionsType.class,
                                       value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "date-last-inclusion", scope = InvestigatorProgressType.class)
    public JAXBElement<XMLGregorianCalendar> createInvestigatorProgressTypeDateLastInclusion(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InvestigatorProgressTypeDateLastInclusion_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InvestigatorProgressType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "date-receipt-protocole", scope = InvestigatorProgressType.class)
    public JAXBElement<XMLGregorianCalendar> createInvestigatorProgressTypeDateReceiptProtocole(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InvestigatorProgressTypeDateReceiptProtocole_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InvestigatorProgressType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "closing-date", scope = InvestigatorProgressType.class)
    public JAXBElement<XMLGregorianCalendar> createInvestigatorProgressTypeClosingDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InvestigatorProgressTypeClosingDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InvestigatorProgressType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "date-signing-agreement", scope = InvestigatorProgressType.class)
    public JAXBElement<XMLGregorianCalendar> createInvestigatorProgressTypeDateSigningAgreement(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InvestigatorProgressTypeDateSigningAgreement_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InvestigatorProgressType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "actual-end-date", scope = InvestigatorProgressType.class)
    public JAXBElement<XMLGregorianCalendar> createInvestigatorProgressTypeActualEndDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InvestigatorProgressTypeActualEndDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InvestigatorProgressType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "actual-start-date", scope = InvestigatorProgressType.class)
    public JAXBElement<XMLGregorianCalendar> createInvestigatorProgressTypeActualStartDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InvestigatorProgressTypeActualStartDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InvestigatorProgressType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "date-place", scope = InvestigatorProgressType.class)
    public JAXBElement<XMLGregorianCalendar> createInvestigatorProgressTypeDatePlace(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InvestigatorProgressTypeDatePlace_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InvestigatorProgressType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "opinion-date", scope = EthicsCommitteeDeclarationType.class)
    public JAXBElement<XMLGregorianCalendar> createEthicsCommitteeDeclarationTypeOpinionDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._DeclarationTypeOpinionDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     EthicsCommitteeDeclarationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link EthicsCommitteeDeclarationType.AdmissibilityDate }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "admissibility-date", scope = EthicsCommitteeDeclarationType.class)
    public JAXBElement<EthicsCommitteeDeclarationType.AdmissibilityDate> createEthicsCommitteeDeclarationTypeAdmissibilityDate(final EthicsCommitteeDeclarationType.AdmissibilityDate value)
    {
        return new JAXBElement<EthicsCommitteeDeclarationType.AdmissibilityDate>(ObjectFactory._CompetentAuthorityDeclarationTypeAdmissibilityDate_QNAME,
                                                                                 EthicsCommitteeDeclarationType.AdmissibilityDate.class,
                                                                                 EthicsCommitteeDeclarationType.class,
                                                                                 value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "contract-end-date", scope = OrganizationType.class)
    public JAXBElement<XMLGregorianCalendar> createOrganizationTypeContractEndDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._OrganizationTypeContractEndDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     OrganizationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "contract-beginning-date", scope = OrganizationType.class)
    public JAXBElement<XMLGregorianCalendar> createOrganizationTypeContractBeginningDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._OrganizationTypeContractBeginningDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     OrganizationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "cumulation-begining-date", scope = InclusionCumulationType.class)
    public JAXBElement<XMLGregorianCalendar> createInclusionCumulationTypeCumulationBeginingDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InclusionCumulationTypeCumulationBeginingDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InclusionCumulationType.class,
                                                     value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://sigrec.ClinicalTrialApplication.xsd", name = "cumulation-end-date", scope = InclusionCumulationType.class)
    public JAXBElement<XMLGregorianCalendar> createInclusionCumulationTypeCumulationEndDate(final XMLGregorianCalendar value)
    {
        return new JAXBElement<XMLGregorianCalendar>(ObjectFactory._InclusionCumulationTypeCumulationEndDate_QNAME,
                                                     XMLGregorianCalendar.class,
                                                     InclusionCumulationType.class,
                                                     value);
    }

}
