//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for ObjetRechercheType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjetRechercheType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="medicament" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="therapie-cellulaire" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="therapie-genetique" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dm-implantable-actif" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dm-diagnostic-invitro" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dm-autres" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="therapie-chirurgicale" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="imagerie" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="radiotherapie" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="alicament" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nutrition" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="other" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="other-details" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjetRechercheType", propOrder =
{

})
public class ObjetRechercheType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "m\u00e9dicament")
    protected String medicament;
    @XmlElement(name = "th\u00e9rapie-cellulaire")
    protected String therapieCellulaire;
    @XmlElement(name = "th\u00e9rapie-g\u00e9n\u00e9tique")
    protected String therapieGenetique;
    @XmlElement(name = "dm-implantable-actif")
    protected String dmImplantableActif;
    @XmlElement(name = "dm-diagnostic-invitro")
    protected String dmDiagnosticInvitro;
    @XmlElement(name = "dm-autres")
    protected String dmAutres;
    @XmlElement(name = "th\u00e9rapie-chirurgicale")
    protected String therapieChirurgicale;
    protected String imagerie;
    @XmlElement(name = "radioth\u00e9rapie")
    protected String radiotherapie;
    protected String alicament;
    protected String nutrition;
    protected String other;
    @XmlElement(name = "other-details")
    protected String otherDetails;

    /**
     * Gets the value of the medicament property.
     * @return possible object is {@link String }
     */
    public String getMedicament()
    {
        return this.medicament;
    }

    /**
     * Sets the value of the medicament property.
     * @param value allowed object is {@link String }
     */
    public void setMedicament(final String value)
    {
        this.medicament = value;
    }

    /**
     * Gets the value of the therapieCellulaire property.
     * @return possible object is {@link String }
     */
    public String getTherapieCellulaire()
    {
        return this.therapieCellulaire;
    }

    /**
     * Sets the value of the therapieCellulaire property.
     * @param value allowed object is {@link String }
     */
    public void setTherapieCellulaire(final String value)
    {
        this.therapieCellulaire = value;
    }

    /**
     * Gets the value of the therapieGenetique property.
     * @return possible object is {@link String }
     */
    public String getTherapieGenetique()
    {
        return this.therapieGenetique;
    }

    /**
     * Sets the value of the therapieGenetique property.
     * @param value allowed object is {@link String }
     */
    public void setTherapieGenetique(final String value)
    {
        this.therapieGenetique = value;
    }

    /**
     * Gets the value of the dmImplantableActif property.
     * @return possible object is {@link String }
     */
    public String getDmImplantableActif()
    {
        return this.dmImplantableActif;
    }

    /**
     * Sets the value of the dmImplantableActif property.
     * @param value allowed object is {@link String }
     */
    public void setDmImplantableActif(final String value)
    {
        this.dmImplantableActif = value;
    }

    /**
     * Gets the value of the dmDiagnosticInvitro property.
     * @return possible object is {@link String }
     */
    public String getDmDiagnosticInvitro()
    {
        return this.dmDiagnosticInvitro;
    }

    /**
     * Sets the value of the dmDiagnosticInvitro property.
     * @param value allowed object is {@link String }
     */
    public void setDmDiagnosticInvitro(final String value)
    {
        this.dmDiagnosticInvitro = value;
    }

    /**
     * Gets the value of the dmAutres property.
     * @return possible object is {@link String }
     */
    public String getDmAutres()
    {
        return this.dmAutres;
    }

    /**
     * Sets the value of the dmAutres property.
     * @param value allowed object is {@link String }
     */
    public void setDmAutres(final String value)
    {
        this.dmAutres = value;
    }

    /**
     * Gets the value of the therapieChirurgicale property.
     * @return possible object is {@link String }
     */
    public String getTherapieChirurgicale()
    {
        return this.therapieChirurgicale;
    }

    /**
     * Sets the value of the therapieChirurgicale property.
     * @param value allowed object is {@link String }
     */
    public void setTherapieChirurgicale(final String value)
    {
        this.therapieChirurgicale = value;
    }

    /**
     * Gets the value of the imagerie property.
     * @return possible object is {@link String }
     */
    public String getImagerie()
    {
        return this.imagerie;
    }

    /**
     * Sets the value of the imagerie property.
     * @param value allowed object is {@link String }
     */
    public void setImagerie(final String value)
    {
        this.imagerie = value;
    }

    /**
     * Gets the value of the radiotherapie property.
     * @return possible object is {@link String }
     */
    public String getRadiotherapie()
    {
        return this.radiotherapie;
    }

    /**
     * Sets the value of the radiotherapie property.
     * @param value allowed object is {@link String }
     */
    public void setRadiotherapie(final String value)
    {
        this.radiotherapie = value;
    }

    /**
     * Gets the value of the alicament property.
     * @return possible object is {@link String }
     */
    public String getAlicament()
    {
        return this.alicament;
    }

    /**
     * Sets the value of the alicament property.
     * @param value allowed object is {@link String }
     */
    public void setAlicament(final String value)
    {
        this.alicament = value;
    }

    /**
     * Gets the value of the nutrition property.
     * @return possible object is {@link String }
     */
    public String getNutrition()
    {
        return this.nutrition;
    }

    /**
     * Sets the value of the nutrition property.
     * @param value allowed object is {@link String }
     */
    public void setNutrition(final String value)
    {
        this.nutrition = value;
    }

    /**
     * Gets the value of the other property.
     * @return possible object is {@link String }
     */
    public String getOther()
    {
        return this.other;
    }

    /**
     * Sets the value of the other property.
     * @param value allowed object is {@link String }
     */
    public void setOther(final String value)
    {
        this.other = value;
    }

    /**
     * Gets the value of the otherDetails property.
     * @return possible object is {@link String }
     */
    public String getOtherDetails()
    {
        return this.otherDetails;
    }

    /**
     * Sets the value of the otherDetails property.
     * @param value allowed object is {@link String }
     */
    public void setOtherDetails(final String value)
    {
        this.otherDetails = value;
    }

}
