//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for opinionType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="opinionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="favorable" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="favorable-avec-remarques" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="complement-informations" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="defavorable" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="autre" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="other-detail" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "opinionType", propOrder =
{"favorable", "favorableAvecRemarques", "complementInformations", "defavorable", "autre",
 "otherDetail" })
public class OpinionType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    protected String favorable;
    @XmlElement(name = "favorable-avec-remarques")
    protected String favorableAvecRemarques;
    @XmlElement(name = "compl\u00e9ment-informations")
    protected String complementInformations;
    @XmlElement(name = "d\u00e9favorable")
    protected String defavorable;
    protected String autre;
    @XmlElement(name = "other-detail")
    protected String otherDetail;

    /**
     * Gets the value of the favorable property.
     * @return possible object is {@link String }
     */
    public String getFavorable()
    {
        return this.favorable;
    }

    /**
     * Sets the value of the favorable property.
     * @param value allowed object is {@link String }
     */
    public void setFavorable(final String value)
    {
        this.favorable = value;
    }

    /**
     * Gets the value of the favorableAvecRemarques property.
     * @return possible object is {@link String }
     */
    public String getFavorableAvecRemarques()
    {
        return this.favorableAvecRemarques;
    }

    /**
     * Sets the value of the favorableAvecRemarques property.
     * @param value allowed object is {@link String }
     */
    public void setFavorableAvecRemarques(final String value)
    {
        this.favorableAvecRemarques = value;
    }

    /**
     * Gets the value of the complementInformations property.
     * @return possible object is {@link String }
     */
    public String getComplementInformations()
    {
        return this.complementInformations;
    }

    /**
     * Sets the value of the complementInformations property.
     * @param value allowed object is {@link String }
     */
    public void setComplementInformations(final String value)
    {
        this.complementInformations = value;
    }

    /**
     * Gets the value of the defavorable property.
     * @return possible object is {@link String }
     */
    public String getDefavorable()
    {
        return this.defavorable;
    }

    /**
     * Sets the value of the defavorable property.
     * @param value allowed object is {@link String }
     */
    public void setDefavorable(final String value)
    {
        this.defavorable = value;
    }

    /**
     * Gets the value of the autre property.
     * @return possible object is {@link String }
     */
    public String getAutre()
    {
        return this.autre;
    }

    /**
     * Sets the value of the autre property.
     * @param value allowed object is {@link String }
     */
    public void setAutre(final String value)
    {
        this.autre = value;
    }

    /**
     * Gets the value of the otherDetail property.
     * @return possible object is {@link String }
     */
    public String getOtherDetail()
    {
        return this.otherDetail;
    }

    /**
     * Sets the value of the otherDetail property.
     * @param value allowed object is {@link String }
     */
    public void setOtherDetail(final String value)
    {
        this.otherDetail = value;
    }

}
