//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for planned-numbersType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="planned-numbersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="in-member-state" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="in-european-community" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="in-whole-trial" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "planned-numbersType", propOrder =
{

})
public class PlannedNumbersType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "in-member-state")
    protected String inMemberState;
    @XmlElement(name = "in-european-community")
    protected String inEuropeanCommunity;
    @XmlElement(name = "in-whole-trial")
    protected String inWholeTrial;

    /**
     * Gets the value of the inMemberState property.
     * @return possible object is {@link String }
     */
    public String getInMemberState()
    {
        return this.inMemberState;
    }

    /**
     * Sets the value of the inMemberState property.
     * @param value allowed object is {@link String }
     */
    public void setInMemberState(final String value)
    {
        this.inMemberState = value;
    }

    /**
     * Gets the value of the inEuropeanCommunity property.
     * @return possible object is {@link String }
     */
    public String getInEuropeanCommunity()
    {
        return this.inEuropeanCommunity;
    }

    /**
     * Sets the value of the inEuropeanCommunity property.
     * @param value allowed object is {@link String }
     */
    public void setInEuropeanCommunity(final String value)
    {
        this.inEuropeanCommunity = value;
    }

    /**
     * Gets the value of the inWholeTrial property.
     * @return possible object is {@link String }
     */
    public String getInWholeTrial()
    {
        return this.inWholeTrial;
    }

    /**
     * Sets the value of the inWholeTrial property.
     * @param value allowed object is {@link String }
     */
    public void setInWholeTrial(final String value)
    {
        this.inWholeTrial = value;
    }

}
