//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for proposed-clinical-trial-sitesType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="proposed-clinical-trial-sitesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="investigator" type="{http://sigrec.ClinicalTrialApplication.xsd}investigatorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="central-technical-facility" type="{http://sigrec.ClinicalTrialApplication.xsd}central-technical-facilityType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="trial-monitoring-facility" type="{http://sigrec.ClinicalTrialApplication.xsd}trial-monitoring-facilityType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "proposed-clinical-trial-sitesType", propOrder =
{"investigator", "centralTechnicalFacility", "trialMonitoringFacility" })
public class ProposedClinicalTrialSitesType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    protected List<InvestigatorType> investigator;
    @XmlElement(name = "central-technical-facility")
    protected List<CentralTechnicalFacilityType> centralTechnicalFacility;
    @XmlElement(name = "trial-monitoring-facility")
    protected List<TrialMonitoringFacilityType> trialMonitoringFacility;

    /**
     * Gets the value of the investigator property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the investigator property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getInvestigator().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link InvestigatorType }
     */
    public List<InvestigatorType> getInvestigator()
    {
        if (this.investigator == null)
        {
            this.investigator = new ArrayList<InvestigatorType>();
        }
        return this.investigator;
    }

    /**
     * Gets the value of the centralTechnicalFacility property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the centralTechnicalFacility property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCentralTechnicalFacility().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CentralTechnicalFacilityType }
     */
    public List<CentralTechnicalFacilityType> getCentralTechnicalFacility()
    {
        if (this.centralTechnicalFacility == null)
        {
            this.centralTechnicalFacility = new ArrayList<CentralTechnicalFacilityType>();
        }
        return this.centralTechnicalFacility;
    }

    /**
     * Gets the value of the trialMonitoringFacility property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the trialMonitoringFacility property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTrialMonitoringFacility().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrialMonitoringFacilityType }
     */
    public List<TrialMonitoringFacilityType> getTrialMonitoringFacility()
    {
        if (this.trialMonitoringFacility == null)
        {
            this.trialMonitoringFacility = new ArrayList<TrialMonitoringFacilityType>();
        }
        return this.trialMonitoringFacility;
    }

}
