//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.BeanSigrec;
import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for regulatory-informationType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="regulatory-informationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="initial-declaration" type="{http://sigrec.ClinicalTrialApplication.xsd}declaration-initialeType" minOccurs="0"/>
 *         &lt;element name="amendement-information" type="{http://sigrec.ClinicalTrialApplication.xsd}amendement-informationType" minOccurs="0"/>
 *         &lt;element name="communication-information" type="{http://sigrec.ClinicalTrialApplication.xsd}communication-informationType" minOccurs="0"/>
 *         &lt;element name="insurance-information" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="insurance" type="{http://sigrec.ClinicalTrialApplication.xsd}InsuranceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cnil" type="{http://sigrec.ClinicalTrialApplication.xsd}cnilType" minOccurs="0"/>
 *         &lt;element name="cro" type="{http://sigrec.ClinicalTrialApplication.xsd}croType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "regulatory-informationType", propOrder =
{

})
public class RegulatoryInformationType

    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "initial-declaration")
    protected DeclarationInitialeType initialDeclaration;
    @XmlElement(name = "amendement-information")
    protected AmendementInformationType amendementInformation;
    @XmlElement(name = "communication-information")
    protected CommunicationInformationType communicationInformation;
    @XmlElement(name = "insurance-information")
    protected RegulatoryInformationType.InsuranceInformation insuranceInformation;
    protected CnilType cnil;
    protected CroType cro;

    /**
     * Gets the value of the initialDeclaration property.
     * @return possible object is {@link DeclarationInitialeType }
     */
    public DeclarationInitialeType getInitialDeclaration()
    {
        return this.initialDeclaration;
    }

    /**
     * Sets the value of the initialDeclaration property.
     * @param value allowed object is {@link DeclarationInitialeType }
     */
    public void setInitialDeclaration(final DeclarationInitialeType value)
    {
        this.initialDeclaration = value;
    }

    /**
     * Gets the value of the amendementInformation property.
     * @return possible object is {@link AmendementInformationType }
     */
    public AmendementInformationType getAmendementInformation()
    {
        return this.amendementInformation;
    }

    /**
     * Sets the value of the amendementInformation property.
     * @param value allowed object is {@link AmendementInformationType }
     */
    public void setAmendementInformation(final AmendementInformationType value)
    {
        this.amendementInformation = value;
    }

    /**
     * Gets the value of the communicationInformation property.
     * @return possible object is {@link CommunicationInformationType }
     */
    public CommunicationInformationType getCommunicationInformation()
    {
        return this.communicationInformation;
    }

    /**
     * Sets the value of the communicationInformation property.
     * @param value allowed object is {@link CommunicationInformationType }
     */
    public void setCommunicationInformation(final CommunicationInformationType value)
    {
        this.communicationInformation = value;
    }

    /**
     * Gets the value of the insuranceInformation property.
     * @return possible object is {@link RegulatoryInformationType.InsuranceInformation }
     */
    public RegulatoryInformationType.InsuranceInformation getInsuranceInformation()
    {
        return this.insuranceInformation;
    }

    /**
     * Sets the value of the insuranceInformation property.
     * @param value allowed object is {@link RegulatoryInformationType.InsuranceInformation }
     */
    public void setInsuranceInformation(final RegulatoryInformationType.InsuranceInformation value)
    {
        this.insuranceInformation = value;
    }

    /**
     * Gets the value of the cnil property.
     * @return possible object is {@link CnilType }
     */
    public CnilType getCnil()
    {
        return this.cnil;
    }

    /**
     * Sets the value of the cnil property.
     * @param value allowed object is {@link CnilType }
     */
    public void setCnil(final CnilType value)
    {
        this.cnil = value;
    }

    /**
     * Gets the value of the cro property.
     * @return possible object is {@link CroType }
     */
    public CroType getCro()
    {
        return this.cro;
    }

    /**
     * Sets the value of the cro property.
     * @param value allowed object is {@link CroType }
     */
    public void setCro(final CroType value)
    {
        this.cro = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="insurance" type="{http://sigrec.ClinicalTrialApplication.xsd}InsuranceType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    {"insurance" })
    public static class InsuranceInformation
        extends BeanSigrec
        implements Serializable, SigrecElement
    {

        private final static long serialVersionUID = 100L;
        protected List<InsuranceType> insurance;

        /**
         * Gets the value of the insurance property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore
         * any modification you make to the returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the insurance property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getInsurance().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link InsuranceType }
         */
        public List<InsuranceType> getInsurance()
        {
            if (this.insurance == null)
            {
                this.insurance = new ArrayList<InsuranceType>();
            }
            return this.insurance;
        }

    }

}
