//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.BeanSigrec;
import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="multi-trial-echange" type="{http://sigrec.ClinicalTrialApplication.xsd}multi_trial_echangeType" minOccurs="0"/>
 *         &lt;element name="multi-trial" type="{http://sigrec.ClinicalTrialApplication.xsd}multi_trialType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{"multiTrialEchange", "multiTrial" })
@XmlRootElement(name = "sigrec-multi-trials-transfert")
public class SigrecMultiTrialsTransfert
    extends BeanSigrec
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "multi-trial-echange")
    protected MultiTrialEchangeType multiTrialEchange;
    @XmlElement(name = "multi-trial", required = true)
    protected MultiTrialType multiTrial;

    /**
     * Gets the value of the multiTrialEchange property.
     * @return possible object is {@link MultiTrialEchangeType }
     */
    public MultiTrialEchangeType getMultiTrialEchange()
    {
        return this.multiTrialEchange;
    }

    /**
     * Sets the value of the multiTrialEchange property.
     * @param value allowed object is {@link MultiTrialEchangeType }
     */
    public void setMultiTrialEchange(final MultiTrialEchangeType value)
    {
        this.multiTrialEchange = value;
    }

    /**
     * Gets the value of the multiTrial property.
     * @return possible object is {@link MultiTrialType }
     */
    public MultiTrialType getMultiTrial()
    {
        return this.multiTrial;
    }

    /**
     * Sets the value of the multiTrial property.
     * @param value allowed object is {@link MultiTrialType }
     */
    public void setMultiTrial(final MultiTrialType value)
    {
        this.multiTrial = value;
    }

}
