//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for sigrec_transfert_info_type complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sigrec_transfert_info_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="number-of-echange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="number-of-trial" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sigrec_transfert_info_type", propOrder =
{"numberOfEchange", "numberOfTrial" })
public class SigrecTransfertInfoType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "number-of-echange", required = true)
    protected String numberOfEchange;
    @XmlElement(name = "number-of-trial")
    protected BigInteger numberOfTrial;

    /**
     * Gets the value of the numberOfEchange property.
     * @return possible object is {@link String }
     */
    public String getNumberOfEchange()
    {
        return this.numberOfEchange;
    }

    /**
     * Sets the value of the numberOfEchange property.
     * @param value allowed object is {@link String }
     */
    public void setNumberOfEchange(final String value)
    {
        this.numberOfEchange = value;
    }

    /**
     * Gets the value of the numberOfTrial property.
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getNumberOfTrial()
    {
        return this.numberOfTrial;
    }

    /**
     * Sets the value of the numberOfTrial property.
     * @param value allowed object is {@link BigInteger }
     */
    public void setNumberOfTrial(final BigInteger value)
    {
        this.numberOfTrial = value;
    }

}
