//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for trial-type-and-phaseType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trial-type-and-phaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="phase-one" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="phase-two" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="phase-two-a" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="phase-two-b" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="phase-three" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="phase-four" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="first-human-administration" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="bioequivalence-study" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="other-phase" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="other-phase-details" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trial-type-and-phaseType", propOrder =
{

})
public class TrialTypeAndPhaseType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "phase-one")
    protected String phaseOne;
    @XmlElement(name = "phase-two")
    protected String phaseTwo;
    @XmlElement(name = "phase-two-a")
    protected String phaseTwoA;
    @XmlElement(name = "phase-two-b")
    protected String phaseTwoB;
    @XmlElement(name = "phase-three")
    protected String phaseThree;
    @XmlElement(name = "phase-four")
    protected String phaseFour;
    @XmlElement(name = "first-human-administration")
    protected String firstHumanAdministration;
    @XmlElement(name = "bioequivalence-study")
    protected String bioequivalenceStudy;
    @XmlElement(name = "other-phase")
    protected String otherPhase;
    @XmlElement(name = "other-phase-details")
    protected String otherPhaseDetails;

    /**
     * Gets the value of the phaseOne property.
     * @return possible object is {@link String }
     */
    public String getPhaseOne()
    {
        return this.phaseOne;
    }

    /**
     * Sets the value of the phaseOne property.
     * @param value allowed object is {@link String }
     */
    public void setPhaseOne(final String value)
    {
        this.phaseOne = value;
    }

    /**
     * Gets the value of the phaseTwo property.
     * @return possible object is {@link String }
     */
    public String getPhaseTwo()
    {
        return this.phaseTwo;
    }

    /**
     * Sets the value of the phaseTwo property.
     * @param value allowed object is {@link String }
     */
    public void setPhaseTwo(final String value)
    {
        this.phaseTwo = value;
    }

    /**
     * Gets the value of the phaseTwoA property.
     * @return possible object is {@link String }
     */
    public String getPhaseTwoA()
    {
        return this.phaseTwoA;
    }

    /**
     * Sets the value of the phaseTwoA property.
     * @param value allowed object is {@link String }
     */
    public void setPhaseTwoA(final String value)
    {
        this.phaseTwoA = value;
    }

    /**
     * Gets the value of the phaseTwoB property.
     * @return possible object is {@link String }
     */
    public String getPhaseTwoB()
    {
        return this.phaseTwoB;
    }

    /**
     * Sets the value of the phaseTwoB property.
     * @param value allowed object is {@link String }
     */
    public void setPhaseTwoB(final String value)
    {
        this.phaseTwoB = value;
    }

    /**
     * Gets the value of the phaseThree property.
     * @return possible object is {@link String }
     */
    public String getPhaseThree()
    {
        return this.phaseThree;
    }

    /**
     * Sets the value of the phaseThree property.
     * @param value allowed object is {@link String }
     */
    public void setPhaseThree(final String value)
    {
        this.phaseThree = value;
    }

    /**
     * Gets the value of the phaseFour property.
     * @return possible object is {@link String }
     */
    public String getPhaseFour()
    {
        return this.phaseFour;
    }

    /**
     * Sets the value of the phaseFour property.
     * @param value allowed object is {@link String }
     */
    public void setPhaseFour(final String value)
    {
        this.phaseFour = value;
    }

    /**
     * Gets the value of the firstHumanAdministration property.
     * @return possible object is {@link String }
     */
    public String getFirstHumanAdministration()
    {
        return this.firstHumanAdministration;
    }

    /**
     * Sets the value of the firstHumanAdministration property.
     * @param value allowed object is {@link String }
     */
    public void setFirstHumanAdministration(final String value)
    {
        this.firstHumanAdministration = value;
    }

    /**
     * Gets the value of the bioequivalenceStudy property.
     * @return possible object is {@link String }
     */
    public String getBioequivalenceStudy()
    {
        return this.bioequivalenceStudy;
    }

    /**
     * Sets the value of the bioequivalenceStudy property.
     * @param value allowed object is {@link String }
     */
    public void setBioequivalenceStudy(final String value)
    {
        this.bioequivalenceStudy = value;
    }

    /**
     * Gets the value of the otherPhase property.
     * @return possible object is {@link String }
     */
    public String getOtherPhase()
    {
        return this.otherPhase;
    }

    /**
     * Sets the value of the otherPhase property.
     * @param value allowed object is {@link String }
     */
    public void setOtherPhase(final String value)
    {
        this.otherPhase = value;
    }

    /**
     * Gets the value of the otherPhaseDetails property.
     * @return possible object is {@link String }
     */
    public String getOtherPhaseDetails()
    {
        return this.otherPhaseDetails;
    }

    /**
     * Sets the value of the otherPhaseDetails property.
     * @param value allowed object is {@link String }
     */
    public void setOtherPhaseDetails(final String value)
    {
        this.otherPhaseDetails = value;
    }

}
