//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.BeanSigrec;
import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for trialType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trialType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="sponsor-information" type="{http://sigrec.ClinicalTrialApplication.xsd}sponsor-informationType" minOccurs="0"/>
 *         &lt;element name="trial-identification" type="{http://sigrec.ClinicalTrialApplication.xsd}TrialIdentificationType" minOccurs="0"/>
 *         &lt;element name="general-information" type="{http://sigrec.ClinicalTrialApplication.xsd}general-informationType" minOccurs="0"/>
 *         &lt;element name="regulatory-information" type="{http://sigrec.ClinicalTrialApplication.xsd}regulatory-informationType" minOccurs="0"/>
 *         &lt;element name="proposed-clinical-trial-sites" type="{http://sigrec.ClinicalTrialApplication.xsd}proposed-clinical-trial-sitesType" minOccurs="0"/>
 *         &lt;element name="dispositif-medical-information" type="{http://sigrec.ClinicalTrialApplication.xsd}dispositif-medical-informationType" minOccurs="0"/>
 *         &lt;element name="medicinal-products" type="{http://sigrec.ClinicalTrialApplication.xsd}medicinal-productsType" minOccurs="0"/>
 *         &lt;element name="population-of-trial-subjects" type="{http://sigrec.ClinicalTrialApplication.xsd}population-of-trial-subjectsType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="trial-sigrec-identification" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="trial-interne-identification" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemaversion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trialType", propOrder =
{

})
public class TrialType
    extends BeanSigrec
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "sponsor-information")
    protected SponsorInformationType sponsorInformation;
    @XmlElement(name = "trial-identification")
    protected TrialIdentificationType trialIdentification;
    @XmlElement(name = "general-information")
    protected GeneralInformationType generalInformation;
    @XmlElement(name = "regulatory-information")
    protected RegulatoryInformationType regulatoryInformation;
    @XmlElement(name = "proposed-clinical-trial-sites")
    protected ProposedClinicalTrialSitesType proposedClinicalTrialSites;
    @XmlElement(name = "dispositif-medical-information")
    protected DispositifMedicalInformationType dispositifMedicalInformation;
    @XmlElement(name = "medicinal-products")
    protected MedicinalProductsType medicinalProducts;
    @XmlElement(name = "population-of-trial-subjects")
    protected PopulationOfTrialSubjectsType populationOfTrialSubjects;
    @XmlAttribute(name = "trial-sigrec-identification")
    protected String trialSigrecIdentification;
    @XmlAttribute(name = "trial-interne-identification")
    protected String trialInterneIdentification;
    @XmlAttribute
    protected String schemaversion;

    /**
     * Gets the value of the sponsorInformation property.
     * @return possible object is {@link SponsorInformationType }
     */
    public SponsorInformationType getSponsorInformation()
    {
        return this.sponsorInformation;
    }

    /**
     * Sets the value of the sponsorInformation property.
     * @param value allowed object is {@link SponsorInformationType }
     */
    public void setSponsorInformation(final SponsorInformationType value)
    {
        this.sponsorInformation = value;
    }

    /**
     * Gets the value of the trialIdentification property.
     * @return possible object is {@link TrialIdentificationType }
     */
    public TrialIdentificationType getTrialIdentification()
    {
        return this.trialIdentification;
    }

    /**
     * Sets the value of the trialIdentification property.
     * @param value allowed object is {@link TrialIdentificationType }
     */
    public void setTrialIdentification(final TrialIdentificationType value)
    {
        this.trialIdentification = value;
    }

    /**
     * Gets the value of the generalInformation property.
     * @return possible object is {@link GeneralInformationType }
     */
    public GeneralInformationType getGeneralInformation()
    {
        return this.generalInformation;
    }

    /**
     * Sets the value of the generalInformation property.
     * @param value allowed object is {@link GeneralInformationType }
     */
    public void setGeneralInformation(final GeneralInformationType value)
    {
        this.generalInformation = value;
    }

    /**
     * Gets the value of the regulatoryInformation property.
     * @return possible object is {@link RegulatoryInformationType }
     */
    public RegulatoryInformationType getRegulatoryInformation()
    {
        return this.regulatoryInformation;
    }

    /**
     * Sets the value of the regulatoryInformation property.
     * @param value allowed object is {@link RegulatoryInformationType }
     */
    public void setRegulatoryInformation(final RegulatoryInformationType value)
    {
        this.regulatoryInformation = value;
    }

    /**
     * Gets the value of the proposedClinicalTrialSites property.
     * @return possible object is {@link ProposedClinicalTrialSitesType }
     */
    public ProposedClinicalTrialSitesType getProposedClinicalTrialSites()
    {
        return this.proposedClinicalTrialSites;
    }

    /**
     * Sets the value of the proposedClinicalTrialSites property.
     * @param value allowed object is {@link ProposedClinicalTrialSitesType }
     */
    public void setProposedClinicalTrialSites(final ProposedClinicalTrialSitesType value)
    {
        this.proposedClinicalTrialSites = value;
    }

    /**
     * Gets the value of the dispositifMedicalInformation property.
     * @return possible object is {@link DispositifMedicalInformationType }
     */
    public DispositifMedicalInformationType getDispositifMedicalInformation()
    {
        return this.dispositifMedicalInformation;
    }

    /**
     * Sets the value of the dispositifMedicalInformation property.
     * @param value allowed object is {@link DispositifMedicalInformationType }
     */
    public void setDispositifMedicalInformation(final DispositifMedicalInformationType value)
    {
        this.dispositifMedicalInformation = value;
    }

    /**
     * Gets the value of the medicinalProducts property.
     * @return possible object is {@link MedicinalProductsType }
     */
    public MedicinalProductsType getMedicinalProducts()
    {
        return this.medicinalProducts;
    }

    /**
     * Sets the value of the medicinalProducts property.
     * @param value allowed object is {@link MedicinalProductsType }
     */
    public void setMedicinalProducts(final MedicinalProductsType value)
    {
        this.medicinalProducts = value;
    }

    /**
     * Gets the value of the populationOfTrialSubjects property.
     * @return possible object is {@link PopulationOfTrialSubjectsType }
     */
    public PopulationOfTrialSubjectsType getPopulationOfTrialSubjects()
    {
        return this.populationOfTrialSubjects;
    }

    /**
     * Sets the value of the populationOfTrialSubjects property.
     * @param value allowed object is {@link PopulationOfTrialSubjectsType }
     */
    public void setPopulationOfTrialSubjects(final PopulationOfTrialSubjectsType value)
    {
        this.populationOfTrialSubjects = value;
    }

    /**
     * Gets the value of the trialSigrecIdentification property.
     * @return possible object is {@link String }
     */
    public String getTrialSigrecIdentification()
    {
        return this.trialSigrecIdentification;
    }

    /**
     * Sets the value of the trialSigrecIdentification property.
     * @param value allowed object is {@link String }
     */
    public void setTrialSigrecIdentification(final String value)
    {
        this.trialSigrecIdentification = value;
    }

    /**
     * Gets the value of the trialInterneIdentification property.
     * @return possible object is {@link String }
     */
    public String getTrialInterneIdentification()
    {
        return this.trialInterneIdentification;
    }

    /**
     * Sets the value of the trialInterneIdentification property.
     * @param value allowed object is {@link String }
     */
    public void setTrialInterneIdentification(final String value)
    {
        this.trialInterneIdentification = value;
    }

    /**
     * Gets the value of the schemaversion property.
     * @return possible object is {@link String }
     */
    public String getSchemaversion()
    {
        return this.schemaversion;
    }

    /**
     * Sets the value of the schemaversion property.
     * @param value allowed object is {@link String }
     */
    public void setSchemaversion(final String value)
    {
        this.schemaversion = value;
    }

}
