//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for trial-designType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trial-designType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="single-site" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="multiple-regional" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="paris-idf" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ouest" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="randomised" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="controlled" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="open" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="single-blind" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="double-blind" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="triple-blind" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="parallel-group" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cross-over" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="other-type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="other-type-details" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="comparator" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="comparator-medical-product" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="comparator-placebo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="comparator-other" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="comparator-other-details" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="multiple-site" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="number-of-sites" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="number-of-sites-open" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="number-of-sites-member-states" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="number-of-sites-member-states-open" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="multiple-interregional" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="multiple-member-states" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="multiple-community" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="third-countries" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="number-of-sites-community" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="data-monitoring-committee" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nord-ouest" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="est" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sud-est" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sud-mediterranee" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sud-ouest" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trial-designType", propOrder =
{

})
public class TrialDesignType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "single-site")
    protected String singleSite;
    @XmlElement(name = "multiple-regional")
    protected String multipleRegional;
    @XmlElement(name = "paris-idf")
    protected String parisIdf;
    protected String ouest;
    protected String randomised;
    protected String controlled;
    protected String open;
    @XmlElement(name = "single-blind")
    protected String singleBlind;
    @XmlElement(name = "double-blind")
    protected String doubleBlind;
    @XmlElement(name = "triple-blind")
    protected String tripleBlind;
    @XmlElement(name = "parallel-group")
    protected String parallelGroup;
    @XmlElement(name = "cross-over")
    protected String crossOver;
    @XmlElement(name = "other-type")
    protected String otherType;
    @XmlElement(name = "other-type-details")
    protected String otherTypeDetails;
    protected String comparator;
    @XmlElement(name = "comparator-medical-product")
    protected String comparatorMedicalProduct;
    @XmlElement(name = "comparator-placebo")
    protected String comparatorPlacebo;
    @XmlElement(name = "comparator-other")
    protected String comparatorOther;
    @XmlElement(name = "comparator-other-details")
    protected String comparatorOtherDetails;
    @XmlElement(name = "multiple-site")
    protected String multipleSite;
    @XmlElement(name = "number-of-sites")
    protected String numberOfSites;
    @XmlElement(name = "number-of-sites-open")
    protected String numberOfSitesOpen;
    @XmlElement(name = "number-of-sites-member-states")
    protected String numberOfSitesMemberStates;
    @XmlElement(name = "number-of-sites-member-states-open")
    protected String numberOfSitesMemberStatesOpen;
    @XmlElement(name = "multiple-interregional")
    protected String multipleInterregional;
    @XmlElement(name = "multiple-member-states")
    protected String multipleMemberStates;
    @XmlElement(name = "multiple-community")
    protected String multipleCommunity;
    @XmlElement(name = "third-countries")
    protected String thirdCountries;
    @XmlElement(name = "number-of-sites-community")
    protected String numberOfSitesCommunity;
    @XmlElement(name = "data-monitoring-committee")
    protected String dataMonitoringCommittee;
    @XmlElement(name = "nord-ouest")
    protected String nordOuest;
    protected String est;
    @XmlElement(name = "sud-est")
    protected String sudEst;
    @XmlElement(name = "sud-m\u00e9diterran\u00e9e")
    protected String sudMediterranee;
    @XmlElement(name = "sud-ouest")
    protected String sudOuest;

    /**
     * Gets the value of the singleSite property.
     * @return possible object is {@link String }
     */
    public String getSingleSite()
    {
        return this.singleSite;
    }

    /**
     * Sets the value of the singleSite property.
     * @param value allowed object is {@link String }
     */
    public void setSingleSite(final String value)
    {
        this.singleSite = value;
    }

    /**
     * Gets the value of the multipleRegional property.
     * @return possible object is {@link String }
     */
    public String getMultipleRegional()
    {
        return this.multipleRegional;
    }

    /**
     * Sets the value of the multipleRegional property.
     * @param value allowed object is {@link String }
     */
    public void setMultipleRegional(final String value)
    {
        this.multipleRegional = value;
    }

    /**
     * Gets the value of the parisIdf property.
     * @return possible object is {@link String }
     */
    public String getParisIdf()
    {
        return this.parisIdf;
    }

    /**
     * Sets the value of the parisIdf property.
     * @param value allowed object is {@link String }
     */
    public void setParisIdf(final String value)
    {
        this.parisIdf = value;
    }

    /**
     * Gets the value of the ouest property.
     * @return possible object is {@link String }
     */
    public String getOuest()
    {
        return this.ouest;
    }

    /**
     * Sets the value of the ouest property.
     * @param value allowed object is {@link String }
     */
    public void setOuest(final String value)
    {
        this.ouest = value;
    }

    /**
     * Gets the value of the randomised property.
     * @return possible object is {@link String }
     */
    public String getRandomised()
    {
        return this.randomised;
    }

    /**
     * Sets the value of the randomised property.
     * @param value allowed object is {@link String }
     */
    public void setRandomised(final String value)
    {
        this.randomised = value;
    }

    /**
     * Gets the value of the controlled property.
     * @return possible object is {@link String }
     */
    public String getControlled()
    {
        return this.controlled;
    }

    /**
     * Sets the value of the controlled property.
     * @param value allowed object is {@link String }
     */
    public void setControlled(final String value)
    {
        this.controlled = value;
    }

    /**
     * Gets the value of the open property.
     * @return possible object is {@link String }
     */
    public String getOpen()
    {
        return this.open;
    }

    /**
     * Sets the value of the open property.
     * @param value allowed object is {@link String }
     */
    public void setOpen(final String value)
    {
        this.open = value;
    }

    /**
     * Gets the value of the singleBlind property.
     * @return possible object is {@link String }
     */
    public String getSingleBlind()
    {
        return this.singleBlind;
    }

    /**
     * Sets the value of the singleBlind property.
     * @param value allowed object is {@link String }
     */
    public void setSingleBlind(final String value)
    {
        this.singleBlind = value;
    }

    /**
     * Gets the value of the doubleBlind property.
     * @return possible object is {@link String }
     */
    public String getDoubleBlind()
    {
        return this.doubleBlind;
    }

    /**
     * Sets the value of the doubleBlind property.
     * @param value allowed object is {@link String }
     */
    public void setDoubleBlind(final String value)
    {
        this.doubleBlind = value;
    }

    /**
     * Gets the value of the tripleBlind property.
     * @return possible object is {@link String }
     */
    public String getTripleBlind()
    {
        return this.tripleBlind;
    }

    /**
     * Sets the value of the tripleBlind property.
     * @param value allowed object is {@link String }
     */
    public void setTripleBlind(final String value)
    {
        this.tripleBlind = value;
    }

    /**
     * Gets the value of the parallelGroup property.
     * @return possible object is {@link String }
     */
    public String getParallelGroup()
    {
        return this.parallelGroup;
    }

    /**
     * Sets the value of the parallelGroup property.
     * @param value allowed object is {@link String }
     */
    public void setParallelGroup(final String value)
    {
        this.parallelGroup = value;
    }

    /**
     * Gets the value of the crossOver property.
     * @return possible object is {@link String }
     */
    public String getCrossOver()
    {
        return this.crossOver;
    }

    /**
     * Sets the value of the crossOver property.
     * @param value allowed object is {@link String }
     */
    public void setCrossOver(final String value)
    {
        this.crossOver = value;
    }

    /**
     * Gets the value of the otherType property.
     * @return possible object is {@link String }
     */
    public String getOtherType()
    {
        return this.otherType;
    }

    /**
     * Sets the value of the otherType property.
     * @param value allowed object is {@link String }
     */
    public void setOtherType(final String value)
    {
        this.otherType = value;
    }

    /**
     * Gets the value of the otherTypeDetails property.
     * @return possible object is {@link String }
     */
    public String getOtherTypeDetails()
    {
        return this.otherTypeDetails;
    }

    /**
     * Sets the value of the otherTypeDetails property.
     * @param value allowed object is {@link String }
     */
    public void setOtherTypeDetails(final String value)
    {
        this.otherTypeDetails = value;
    }

    /**
     * Gets the value of the comparator property.
     * @return possible object is {@link String }
     */
    public String getComparator()
    {
        return this.comparator;
    }

    /**
     * Sets the value of the comparator property.
     * @param value allowed object is {@link String }
     */
    public void setComparator(final String value)
    {
        this.comparator = value;
    }

    /**
     * Gets the value of the comparatorMedicalProduct property.
     * @return possible object is {@link String }
     */
    public String getComparatorMedicalProduct()
    {
        return this.comparatorMedicalProduct;
    }

    /**
     * Sets the value of the comparatorMedicalProduct property.
     * @param value allowed object is {@link String }
     */
    public void setComparatorMedicalProduct(final String value)
    {
        this.comparatorMedicalProduct = value;
    }

    /**
     * Gets the value of the comparatorPlacebo property.
     * @return possible object is {@link String }
     */
    public String getComparatorPlacebo()
    {
        return this.comparatorPlacebo;
    }

    /**
     * Sets the value of the comparatorPlacebo property.
     * @param value allowed object is {@link String }
     */
    public void setComparatorPlacebo(final String value)
    {
        this.comparatorPlacebo = value;
    }

    /**
     * Gets the value of the comparatorOther property.
     * @return possible object is {@link String }
     */
    public String getComparatorOther()
    {
        return this.comparatorOther;
    }

    /**
     * Sets the value of the comparatorOther property.
     * @param value allowed object is {@link String }
     */
    public void setComparatorOther(final String value)
    {
        this.comparatorOther = value;
    }

    /**
     * Gets the value of the comparatorOtherDetails property.
     * @return possible object is {@link String }
     */
    public String getComparatorOtherDetails()
    {
        return this.comparatorOtherDetails;
    }

    /**
     * Sets the value of the comparatorOtherDetails property.
     * @param value allowed object is {@link String }
     */
    public void setComparatorOtherDetails(final String value)
    {
        this.comparatorOtherDetails = value;
    }

    /**
     * Gets the value of the multipleSite property.
     * @return possible object is {@link String }
     */
    public String getMultipleSite()
    {
        return this.multipleSite;
    }

    /**
     * Sets the value of the multipleSite property.
     * @param value allowed object is {@link String }
     */
    public void setMultipleSite(final String value)
    {
        this.multipleSite = value;
    }

    /**
     * Gets the value of the numberOfSites property.
     * @return possible object is {@link String }
     */
    public String getNumberOfSites()
    {
        return this.numberOfSites;
    }

    /**
     * Sets the value of the numberOfSites property.
     * @param value allowed object is {@link String }
     */
    public void setNumberOfSites(final String value)
    {
        this.numberOfSites = value;
    }

    /**
     * Gets the value of the numberOfSitesOpen property.
     * @return possible object is {@link String }
     */
    public String getNumberOfSitesOpen()
    {
        return this.numberOfSitesOpen;
    }

    /**
     * Sets the value of the numberOfSitesOpen property.
     * @param value allowed object is {@link String }
     */
    public void setNumberOfSitesOpen(final String value)
    {
        this.numberOfSitesOpen = value;
    }

    /**
     * Gets the value of the numberOfSitesMemberStates property.
     * @return possible object is {@link String }
     */
    public String getNumberOfSitesMemberStates()
    {
        return this.numberOfSitesMemberStates;
    }

    /**
     * Sets the value of the numberOfSitesMemberStates property.
     * @param value allowed object is {@link String }
     */
    public void setNumberOfSitesMemberStates(final String value)
    {
        this.numberOfSitesMemberStates = value;
    }

    /**
     * Gets the value of the numberOfSitesMemberStatesOpen property.
     * @return possible object is {@link String }
     */
    public String getNumberOfSitesMemberStatesOpen()
    {
        return this.numberOfSitesMemberStatesOpen;
    }

    /**
     * Sets the value of the numberOfSitesMemberStatesOpen property.
     * @param value allowed object is {@link String }
     */
    public void setNumberOfSitesMemberStatesOpen(final String value)
    {
        this.numberOfSitesMemberStatesOpen = value;
    }

    /**
     * Gets the value of the multipleInterregional property.
     * @return possible object is {@link String }
     */
    public String getMultipleInterregional()
    {
        return this.multipleInterregional;
    }

    /**
     * Sets the value of the multipleInterregional property.
     * @param value allowed object is {@link String }
     */
    public void setMultipleInterregional(final String value)
    {
        this.multipleInterregional = value;
    }

    /**
     * Gets the value of the multipleMemberStates property.
     * @return possible object is {@link String }
     */
    public String getMultipleMemberStates()
    {
        return this.multipleMemberStates;
    }

    /**
     * Sets the value of the multipleMemberStates property.
     * @param value allowed object is {@link String }
     */
    public void setMultipleMemberStates(final String value)
    {
        this.multipleMemberStates = value;
    }

    /**
     * Gets the value of the multipleCommunity property.
     * @return possible object is {@link String }
     */
    public String getMultipleCommunity()
    {
        return this.multipleCommunity;
    }

    /**
     * Sets the value of the multipleCommunity property.
     * @param value allowed object is {@link String }
     */
    public void setMultipleCommunity(final String value)
    {
        this.multipleCommunity = value;
    }

    /**
     * Gets the value of the thirdCountries property.
     * @return possible object is {@link String }
     */
    public String getThirdCountries()
    {
        return this.thirdCountries;
    }

    /**
     * Sets the value of the thirdCountries property.
     * @param value allowed object is {@link String }
     */
    public void setThirdCountries(final String value)
    {
        this.thirdCountries = value;
    }

    /**
     * Gets the value of the numberOfSitesCommunity property.
     * @return possible object is {@link String }
     */
    public String getNumberOfSitesCommunity()
    {
        return this.numberOfSitesCommunity;
    }

    /**
     * Sets the value of the numberOfSitesCommunity property.
     * @param value allowed object is {@link String }
     */
    public void setNumberOfSitesCommunity(final String value)
    {
        this.numberOfSitesCommunity = value;
    }

    /**
     * Gets the value of the dataMonitoringCommittee property.
     * @return possible object is {@link String }
     */
    public String getDataMonitoringCommittee()
    {
        return this.dataMonitoringCommittee;
    }

    /**
     * Sets the value of the dataMonitoringCommittee property.
     * @param value allowed object is {@link String }
     */
    public void setDataMonitoringCommittee(final String value)
    {
        this.dataMonitoringCommittee = value;
    }

    /**
     * Gets the value of the nordOuest property.
     * @return possible object is {@link String }
     */
    public String getNordOuest()
    {
        return this.nordOuest;
    }

    /**
     * Sets the value of the nordOuest property.
     * @param value allowed object is {@link String }
     */
    public void setNordOuest(final String value)
    {
        this.nordOuest = value;
    }

    /**
     * Gets the value of the est property.
     * @return possible object is {@link String }
     */
    public String getEst()
    {
        return this.est;
    }

    /**
     * Sets the value of the est property.
     * @param value allowed object is {@link String }
     */
    public void setEst(final String value)
    {
        this.est = value;
    }

    /**
     * Gets the value of the sudEst property.
     * @return possible object is {@link String }
     */
    public String getSudEst()
    {
        return this.sudEst;
    }

    /**
     * Sets the value of the sudEst property.
     * @param value allowed object is {@link String }
     */
    public void setSudEst(final String value)
    {
        this.sudEst = value;
    }

    /**
     * Gets the value of the sudMediterranee property.
     * @return possible object is {@link String }
     */
    public String getSudMediterranee()
    {
        return this.sudMediterranee;
    }

    /**
     * Sets the value of the sudMediterranee property.
     * @param value allowed object is {@link String }
     */
    public void setSudMediterranee(final String value)
    {
        this.sudMediterranee = value;
    }

    /**
     * Gets the value of the sudOuest property.
     * @return possible object is {@link String }
     */
    public String getSudOuest()
    {
        return this.sudOuest;
    }

    /**
     * Sets the value of the sudOuest property.
     * @param value allowed object is {@link String }
     */
    public void setSudOuest(final String value)
    {
        this.sudOuest = value;
    }

}
