//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for trial-monitoring-facilityType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trial-monitoring-facilityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="organisation-name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="organisation-department-name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="contact-details" type="{http://sigrec.ClinicalTrialApplication.xsd}ContactDetailsType" minOccurs="0"/>
 *         &lt;element name="duty-sponsor-tasks" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duty-monitoring" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duty-data-management" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duty-edata-capture" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duty-ivrs-treatment" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duty-medical-writing" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duty-susar-reporting" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duty-regulatory-aid" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duty-quality-assurance-auditing" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="statistical-analysis" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duty-investigator-recruitment" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duty-other-duties" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duty-other-duties-descriptions" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="node-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trial-monitoring-facilityType", propOrder =
{"organisationName", "organisationDepartmentName", "contactDetails", "dutySponsorTasks",
 "dutyMonitoring", "dutyDataManagement", "dutyEdataCapture", "dutyIvrsTreatment",
 "dutyMedicalWriting", "dutySusarReporting", "dutyRegulatoryAid", "dutyQualityAssuranceAuditing",
 "statisticalAnalysis", "dutyInvestigatorRecruitment", "dutyOtherDuties",
 "dutyOtherDutiesDescriptions" })
public class TrialMonitoringFacilityType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "organisation-name")
    protected String organisationName;
    @XmlElement(name = "organisation-department-name")
    protected String organisationDepartmentName;
    @XmlElement(name = "contact-details")
    protected ContactDetailsType contactDetails;
    @XmlElement(name = "duty-sponsor-tasks")
    protected String dutySponsorTasks;
    @XmlElement(name = "duty-monitoring")
    protected String dutyMonitoring;
    @XmlElement(name = "duty-data-management")
    protected String dutyDataManagement;
    @XmlElement(name = "duty-edata-capture")
    protected String dutyEdataCapture;
    @XmlElement(name = "duty-ivrs-treatment")
    protected String dutyIvrsTreatment;
    @XmlElement(name = "duty-medical-writing")
    protected String dutyMedicalWriting;
    @XmlElement(name = "duty-susar-reporting")
    protected String dutySusarReporting;
    @XmlElement(name = "duty-regulatory-aid")
    protected String dutyRegulatoryAid;
    @XmlElement(name = "duty-quality-assurance-auditing")
    protected String dutyQualityAssuranceAuditing;
    @XmlElement(name = "statistical-analysis")
    protected String statisticalAnalysis;
    @XmlElement(name = "duty-investigator-recruitment")
    protected String dutyInvestigatorRecruitment;
    @XmlElement(name = "duty-other-duties")
    protected String dutyOtherDuties;
    @XmlElement(name = "duty-other-duties-descriptions")
    protected String dutyOtherDutiesDescriptions;
    @XmlAttribute(name = "node-id")
    protected String nodeId;

    /**
     * Gets the value of the organisationName property.
     * @return possible object is {@link String }
     */
    public String getOrganisationName()
    {
        return this.organisationName;
    }

    /**
     * Sets the value of the organisationName property.
     * @param value allowed object is {@link String }
     */
    public void setOrganisationName(final String value)
    {
        this.organisationName = value;
    }

    /**
     * Gets the value of the organisationDepartmentName property.
     * @return possible object is {@link String }
     */
    public String getOrganisationDepartmentName()
    {
        return this.organisationDepartmentName;
    }

    /**
     * Sets the value of the organisationDepartmentName property.
     * @param value allowed object is {@link String }
     */
    public void setOrganisationDepartmentName(final String value)
    {
        this.organisationDepartmentName = value;
    }

    /**
     * Gets the value of the contactDetails property.
     * @return possible object is {@link ContactDetailsType }
     */
    public ContactDetailsType getContactDetails()
    {
        return this.contactDetails;
    }

    /**
     * Sets the value of the contactDetails property.
     * @param value allowed object is {@link ContactDetailsType }
     */
    public void setContactDetails(final ContactDetailsType value)
    {
        this.contactDetails = value;
    }

    /**
     * Gets the value of the dutySponsorTasks property.
     * @return possible object is {@link String }
     */
    public String getDutySponsorTasks()
    {
        return this.dutySponsorTasks;
    }

    /**
     * Sets the value of the dutySponsorTasks property.
     * @param value allowed object is {@link String }
     */
    public void setDutySponsorTasks(final String value)
    {
        this.dutySponsorTasks = value;
    }

    /**
     * Gets the value of the dutyMonitoring property.
     * @return possible object is {@link String }
     */
    public String getDutyMonitoring()
    {
        return this.dutyMonitoring;
    }

    /**
     * Sets the value of the dutyMonitoring property.
     * @param value allowed object is {@link String }
     */
    public void setDutyMonitoring(final String value)
    {
        this.dutyMonitoring = value;
    }

    /**
     * Gets the value of the dutyDataManagement property.
     * @return possible object is {@link String }
     */
    public String getDutyDataManagement()
    {
        return this.dutyDataManagement;
    }

    /**
     * Sets the value of the dutyDataManagement property.
     * @param value allowed object is {@link String }
     */
    public void setDutyDataManagement(final String value)
    {
        this.dutyDataManagement = value;
    }

    /**
     * Gets the value of the dutyEdataCapture property.
     * @return possible object is {@link String }
     */
    public String getDutyEdataCapture()
    {
        return this.dutyEdataCapture;
    }

    /**
     * Sets the value of the dutyEdataCapture property.
     * @param value allowed object is {@link String }
     */
    public void setDutyEdataCapture(final String value)
    {
        this.dutyEdataCapture = value;
    }

    /**
     * Gets the value of the dutyIvrsTreatment property.
     * @return possible object is {@link String }
     */
    public String getDutyIvrsTreatment()
    {
        return this.dutyIvrsTreatment;
    }

    /**
     * Sets the value of the dutyIvrsTreatment property.
     * @param value allowed object is {@link String }
     */
    public void setDutyIvrsTreatment(final String value)
    {
        this.dutyIvrsTreatment = value;
    }

    /**
     * Gets the value of the dutyMedicalWriting property.
     * @return possible object is {@link String }
     */
    public String getDutyMedicalWriting()
    {
        return this.dutyMedicalWriting;
    }

    /**
     * Sets the value of the dutyMedicalWriting property.
     * @param value allowed object is {@link String }
     */
    public void setDutyMedicalWriting(final String value)
    {
        this.dutyMedicalWriting = value;
    }

    /**
     * Gets the value of the dutySusarReporting property.
     * @return possible object is {@link String }
     */
    public String getDutySusarReporting()
    {
        return this.dutySusarReporting;
    }

    /**
     * Sets the value of the dutySusarReporting property.
     * @param value allowed object is {@link String }
     */
    public void setDutySusarReporting(final String value)
    {
        this.dutySusarReporting = value;
    }

    /**
     * Gets the value of the dutyRegulatoryAid property.
     * @return possible object is {@link String }
     */
    public String getDutyRegulatoryAid()
    {
        return this.dutyRegulatoryAid;
    }

    /**
     * Sets the value of the dutyRegulatoryAid property.
     * @param value allowed object is {@link String }
     */
    public void setDutyRegulatoryAid(final String value)
    {
        this.dutyRegulatoryAid = value;
    }

    /**
     * Gets the value of the dutyQualityAssuranceAuditing property.
     * @return possible object is {@link String }
     */
    public String getDutyQualityAssuranceAuditing()
    {
        return this.dutyQualityAssuranceAuditing;
    }

    /**
     * Sets the value of the dutyQualityAssuranceAuditing property.
     * @param value allowed object is {@link String }
     */
    public void setDutyQualityAssuranceAuditing(final String value)
    {
        this.dutyQualityAssuranceAuditing = value;
    }

    /**
     * Gets the value of the statisticalAnalysis property.
     * @return possible object is {@link String }
     */
    public String getStatisticalAnalysis()
    {
        return this.statisticalAnalysis;
    }

    /**
     * Sets the value of the statisticalAnalysis property.
     * @param value allowed object is {@link String }
     */
    public void setStatisticalAnalysis(final String value)
    {
        this.statisticalAnalysis = value;
    }

    /**
     * Gets the value of the dutyInvestigatorRecruitment property.
     * @return possible object is {@link String }
     */
    public String getDutyInvestigatorRecruitment()
    {
        return this.dutyInvestigatorRecruitment;
    }

    /**
     * Sets the value of the dutyInvestigatorRecruitment property.
     * @param value allowed object is {@link String }
     */
    public void setDutyInvestigatorRecruitment(final String value)
    {
        this.dutyInvestigatorRecruitment = value;
    }

    /**
     * Gets the value of the dutyOtherDuties property.
     * @return possible object is {@link String }
     */
    public String getDutyOtherDuties()
    {
        return this.dutyOtherDuties;
    }

    /**
     * Sets the value of the dutyOtherDuties property.
     * @param value allowed object is {@link String }
     */
    public void setDutyOtherDuties(final String value)
    {
        this.dutyOtherDuties = value;
    }

    /**
     * Gets the value of the dutyOtherDutiesDescriptions property.
     * @return possible object is {@link String }
     */
    public String getDutyOtherDutiesDescriptions()
    {
        return this.dutyOtherDutiesDescriptions;
    }

    /**
     * Sets the value of the dutyOtherDutiesDescriptions property.
     * @param value allowed object is {@link String }
     */
    public void setDutyOtherDutiesDescriptions(final String value)
    {
        this.dutyOtherDutiesDescriptions = value;
    }

    /**
     * Gets the value of the nodeId property.
     * @return possible object is {@link String }
     */
    public String getNodeId()
    {
        return this.nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * @param value allowed object is {@link String }
     */
    public void setNodeId(final String value)
    {
        this.nodeId = value;
    }

}
