//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for trial-scopeType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trial-scopeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="diagnosis" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="prophylaxis" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="therapy" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="safety" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="efficiacy" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pharmacokinetic" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pharmacodynamic" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pharmacogenomic" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pharmacogenetic" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pharmacoeconomic" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="bioequivalence" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dose-response" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pharmacologie" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="therapeutique" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pronostique" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="diagnostique" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="physiologie" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="physiopathologie" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="prevention" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="depistage" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="genetique" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="epidemiologie" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="other" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="other-details" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trial-scopeType", propOrder =
{

})
public class TrialScopeType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    protected String diagnosis;
    protected String prophylaxis;
    protected String therapy;
    protected String safety;
    protected String efficiacy;
    protected String pharmacokinetic;
    protected String pharmacodynamic;
    protected String pharmacogenomic;
    protected String pharmacogenetic;
    protected String pharmacoeconomic;
    protected String bioequivalence;
    @XmlElement(name = "dose-response")
    protected String doseResponse;
    protected String pharmacologie;
    @XmlElement(name = "th\u00e9rapeutique")
    protected String therapeutique;
    protected String pronostique;
    protected String diagnostique;
    protected String physiologie;
    protected String physiopathologie;
    @XmlElement(name = "pr\u00e9vention")
    protected String prevention;
    @XmlElement(name = "d\u00e9pistage")
    protected String depistage;
    @XmlElement(name = "g\u00e9n\u00e9tique")
    protected String genetique;
    @XmlElement(name = "epid\u00e9miologie")
    protected String epidemiologie;
    protected String other;
    @XmlElement(name = "other-details")
    protected String otherDetails;

    /**
     * Gets the value of the diagnosis property.
     * @return possible object is {@link String }
     */
    public String getDiagnosis()
    {
        return this.diagnosis;
    }

    /**
     * Sets the value of the diagnosis property.
     * @param value allowed object is {@link String }
     */
    public void setDiagnosis(final String value)
    {
        this.diagnosis = value;
    }

    /**
     * Gets the value of the prophylaxis property.
     * @return possible object is {@link String }
     */
    public String getProphylaxis()
    {
        return this.prophylaxis;
    }

    /**
     * Sets the value of the prophylaxis property.
     * @param value allowed object is {@link String }
     */
    public void setProphylaxis(final String value)
    {
        this.prophylaxis = value;
    }

    /**
     * Gets the value of the therapy property.
     * @return possible object is {@link String }
     */
    public String getTherapy()
    {
        return this.therapy;
    }

    /**
     * Sets the value of the therapy property.
     * @param value allowed object is {@link String }
     */
    public void setTherapy(final String value)
    {
        this.therapy = value;
    }

    /**
     * Gets the value of the safety property.
     * @return possible object is {@link String }
     */
    public String getSafety()
    {
        return this.safety;
    }

    /**
     * Sets the value of the safety property.
     * @param value allowed object is {@link String }
     */
    public void setSafety(final String value)
    {
        this.safety = value;
    }

    /**
     * Gets the value of the efficiacy property.
     * @return possible object is {@link String }
     */
    public String getEfficiacy()
    {
        return this.efficiacy;
    }

    /**
     * Sets the value of the efficiacy property.
     * @param value allowed object is {@link String }
     */
    public void setEfficiacy(final String value)
    {
        this.efficiacy = value;
    }

    /**
     * Gets the value of the pharmacokinetic property.
     * @return possible object is {@link String }
     */
    public String getPharmacokinetic()
    {
        return this.pharmacokinetic;
    }

    /**
     * Sets the value of the pharmacokinetic property.
     * @param value allowed object is {@link String }
     */
    public void setPharmacokinetic(final String value)
    {
        this.pharmacokinetic = value;
    }

    /**
     * Gets the value of the pharmacodynamic property.
     * @return possible object is {@link String }
     */
    public String getPharmacodynamic()
    {
        return this.pharmacodynamic;
    }

    /**
     * Sets the value of the pharmacodynamic property.
     * @param value allowed object is {@link String }
     */
    public void setPharmacodynamic(final String value)
    {
        this.pharmacodynamic = value;
    }

    /**
     * Gets the value of the pharmacogenomic property.
     * @return possible object is {@link String }
     */
    public String getPharmacogenomic()
    {
        return this.pharmacogenomic;
    }

    /**
     * Sets the value of the pharmacogenomic property.
     * @param value allowed object is {@link String }
     */
    public void setPharmacogenomic(final String value)
    {
        this.pharmacogenomic = value;
    }

    /**
     * Gets the value of the pharmacogenetic property.
     * @return possible object is {@link String }
     */
    public String getPharmacogenetic()
    {
        return this.pharmacogenetic;
    }

    /**
     * Sets the value of the pharmacogenetic property.
     * @param value allowed object is {@link String }
     */
    public void setPharmacogenetic(final String value)
    {
        this.pharmacogenetic = value;
    }

    /**
     * Gets the value of the pharmacoeconomic property.
     * @return possible object is {@link String }
     */
    public String getPharmacoeconomic()
    {
        return this.pharmacoeconomic;
    }

    /**
     * Sets the value of the pharmacoeconomic property.
     * @param value allowed object is {@link String }
     */
    public void setPharmacoeconomic(final String value)
    {
        this.pharmacoeconomic = value;
    }

    /**
     * Gets the value of the bioequivalence property.
     * @return possible object is {@link String }
     */
    public String getBioequivalence()
    {
        return this.bioequivalence;
    }

    /**
     * Sets the value of the bioequivalence property.
     * @param value allowed object is {@link String }
     */
    public void setBioequivalence(final String value)
    {
        this.bioequivalence = value;
    }

    /**
     * Gets the value of the doseResponse property.
     * @return possible object is {@link String }
     */
    public String getDoseResponse()
    {
        return this.doseResponse;
    }

    /**
     * Sets the value of the doseResponse property.
     * @param value allowed object is {@link String }
     */
    public void setDoseResponse(final String value)
    {
        this.doseResponse = value;
    }

    /**
     * Gets the value of the pharmacologie property.
     * @return possible object is {@link String }
     */
    public String getPharmacologie()
    {
        return this.pharmacologie;
    }

    /**
     * Sets the value of the pharmacologie property.
     * @param value allowed object is {@link String }
     */
    public void setPharmacologie(final String value)
    {
        this.pharmacologie = value;
    }

    /**
     * Gets the value of the therapeutique property.
     * @return possible object is {@link String }
     */
    public String getTherapeutique()
    {
        return this.therapeutique;
    }

    /**
     * Sets the value of the therapeutique property.
     * @param value allowed object is {@link String }
     */
    public void setTherapeutique(final String value)
    {
        this.therapeutique = value;
    }

    /**
     * Gets the value of the pronostique property.
     * @return possible object is {@link String }
     */
    public String getPronostique()
    {
        return this.pronostique;
    }

    /**
     * Sets the value of the pronostique property.
     * @param value allowed object is {@link String }
     */
    public void setPronostique(final String value)
    {
        this.pronostique = value;
    }

    /**
     * Gets the value of the diagnostique property.
     * @return possible object is {@link String }
     */
    public String getDiagnostique()
    {
        return this.diagnostique;
    }

    /**
     * Sets the value of the diagnostique property.
     * @param value allowed object is {@link String }
     */
    public void setDiagnostique(final String value)
    {
        this.diagnostique = value;
    }

    /**
     * Gets the value of the physiologie property.
     * @return possible object is {@link String }
     */
    public String getPhysiologie()
    {
        return this.physiologie;
    }

    /**
     * Sets the value of the physiologie property.
     * @param value allowed object is {@link String }
     */
    public void setPhysiologie(final String value)
    {
        this.physiologie = value;
    }

    /**
     * Gets the value of the physiopathologie property.
     * @return possible object is {@link String }
     */
    public String getPhysiopathologie()
    {
        return this.physiopathologie;
    }

    /**
     * Sets the value of the physiopathologie property.
     * @param value allowed object is {@link String }
     */
    public void setPhysiopathologie(final String value)
    {
        this.physiopathologie = value;
    }

    /**
     * Gets the value of the prevention property.
     * @return possible object is {@link String }
     */
    public String getPrevention()
    {
        return this.prevention;
    }

    /**
     * Sets the value of the prevention property.
     * @param value allowed object is {@link String }
     */
    public void setPrevention(final String value)
    {
        this.prevention = value;
    }

    /**
     * Gets the value of the depistage property.
     * @return possible object is {@link String }
     */
    public String getDepistage()
    {
        return this.depistage;
    }

    /**
     * Sets the value of the depistage property.
     * @param value allowed object is {@link String }
     */
    public void setDepistage(final String value)
    {
        this.depistage = value;
    }

    /**
     * Gets the value of the genetique property.
     * @return possible object is {@link String }
     */
    public String getGenetique()
    {
        return this.genetique;
    }

    /**
     * Sets the value of the genetique property.
     * @param value allowed object is {@link String }
     */
    public void setGenetique(final String value)
    {
        this.genetique = value;
    }

    /**
     * Gets the value of the epidemiologie property.
     * @return possible object is {@link String }
     */
    public String getEpidemiologie()
    {
        return this.epidemiologie;
    }

    /**
     * Sets the value of the epidemiologie property.
     * @param value allowed object is {@link String }
     */
    public void setEpidemiologie(final String value)
    {
        this.epidemiologie = value;
    }

    /**
     * Gets the value of the other property.
     * @return possible object is {@link String }
     */
    public String getOther()
    {
        return this.other;
    }

    /**
     * Sets the value of the other property.
     * @param value allowed object is {@link String }
     */
    public void setOther(final String value)
    {
        this.other = value;
    }

    /**
     * Gets the value of the otherDetails property.
     * @return possible object is {@link String }
     */
    public String getOtherDetails()
    {
        return this.otherDetails;
    }

    /**
     * Sets the value of the otherDetails property.
     * @param value allowed object is {@link String }
     */
    public void setOtherDetails(final String value)
    {
        this.otherDetails = value;
    }

}
