//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.11.08 at 10:05:49 AM CET
//

package fr.pharma.eclipse.domain.model.sigrec;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fr.pharma.eclipse.domain.model.sigrec.common.SigrecElement;

/**
 * <p>
 * Java class for TypeRechercheType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeRechercheType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="recherche-biomedicale" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="soins-courants" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="observationnelle" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sur-donnees" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="collections-biologiques" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeRechercheType", propOrder =
{

})
public class TypeRechercheType
    
    implements Serializable, SigrecElement
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "recherche-biom\u00e9dicale")
    protected String rechercheBiomedicale;
    @XmlElement(name = "soins-courants")
    protected String soinsCourants;
    protected String observationnelle;
    @XmlElement(name = "sur-donn\u00e9es")
    protected String surDonnees;
    @XmlElement(name = "collections-biologiques")
    protected String collectionsBiologiques;

    /**
     * Gets the value of the rechercheBiomedicale property.
     * @return possible object is {@link String }
     */
    public String getRechercheBiomedicale()
    {
        return this.rechercheBiomedicale;
    }

    /**
     * Sets the value of the rechercheBiomedicale property.
     * @param value allowed object is {@link String }
     */
    public void setRechercheBiomedicale(final String value)
    {
        this.rechercheBiomedicale = value;
    }

    /**
     * Gets the value of the soinsCourants property.
     * @return possible object is {@link String }
     */
    public String getSoinsCourants()
    {
        return this.soinsCourants;
    }

    /**
     * Sets the value of the soinsCourants property.
     * @param value allowed object is {@link String }
     */
    public void setSoinsCourants(final String value)
    {
        this.soinsCourants = value;
    }

    /**
     * Gets the value of the observationnelle property.
     * @return possible object is {@link String }
     */
    public String getObservationnelle()
    {
        return this.observationnelle;
    }

    /**
     * Sets the value of the observationnelle property.
     * @param value allowed object is {@link String }
     */
    public void setObservationnelle(final String value)
    {
        this.observationnelle = value;
    }

    /**
     * Gets the value of the surDonnees property.
     * @return possible object is {@link String }
     */
    public String getSurDonnees()
    {
        return this.surDonnees;
    }

    /**
     * Sets the value of the surDonnees property.
     * @param value allowed object is {@link String }
     */
    public void setSurDonnees(final String value)
    {
        this.surDonnees = value;
    }

    /**
     * Gets the value of the collectionsBiologiques property.
     * @return possible object is {@link String }
     */
    public String getCollectionsBiologiques()
    {
        return this.collectionsBiologiques;
    }

    /**
     * Sets the value of the collectionsBiologiques property.
     * @param value allowed object is {@link String }
     */
    public void setCollectionsBiologiques(final String value)
    {
        this.collectionsBiologiques = value;
    }

}
